### ISSUE TITLE
Getting teleported back to spawn when i get 500 blocks away

### ISSUE THREAD

**Issue by Cnights** [NillerMedDild/Enigmatica2ExpertSkyblock#104]
#### Crash Report: No crash report

[pastebin/gist/etc link here]

**Comment by Cnights** [comment]
Found the issue is caused by Void Island Control. There is a line in the config that sets the max distance you can be from your island. Adjusted it in the config as I am running a multiplayer server for me and my teammate.

**Comment by BluePanda13** [comment]
there is a line where u can disable protection so do it and everything will be fine
