### ISSUE TITLE
TE sawmill give 3 planks per log

### ISSUE THREAD

**Issue by syrun97** [NillerMedDild/Enigmatica2ExpertSkyblock#105]
#### Issue Description
TE sawmill give 3 planks per log, 
but mekanism one(that craft ingredent of TE one) give 6 planks per log.
#### Modpack version (Do not use "latest")
1.3a
#### Crash Report
not crash
[pastebin/gist/etc link here]
![2018-08-20_13 03 09](https://user-images.githubusercontent.com/19798397/44320117-f5b44e80-a47a-11e8-92b3-434c285a50f5.png)
![2018-08-20_13 03 13](https://user-images.githubusercontent.com/19798397/44320118-f5b44e80-a47a-11e8-8102-200dbca556ea.png)
![2018-08-20_13 03 17](https://user-images.githubusercontent.com/19798397/44320124-fcdb5c80-a47a-11e8-9ac0-7280a8c77922.png)

**Comment by NillerMedDild** [comment]
I'm not sure what's causing this, but I suggest you just avoid the machine. I don't have the time to fix this, at the moment at least.

**Comment by Gimpler** [comment]
I found the issue.  It's because of the TE dev hardcoding sawmill recipes to be 1.5x the crafting table one.

**Comment by NillerMedDild** [comment]
Oh I see.
