### ISSUE TITLE
Missing bucket in Creative Tank recipe due to missing mod

### ISSUE THREAD

**Issue by GuntherDW** [NillerMedDild/Enigmatica2ExpertSkyblock#132]
#### Issue Description

Currently, the top left bucket in the recipe for the creative tank requires a bucket of liquid from a mod that, while included in the overworld version, is not in the skyblock version.

The top left bucket in the recipe wants a "milk_goat" bucket.
But because animania from the overworld version isn't included in the pack this makes it so the creative tank isn't craftable.

For reference: The bucket of milk you get by milking a cow is "minecraft:milk_bucket".

![ingame recipe screenshot](https://i.imgur.com/bP7q0J5.png)

EDIT: Checked the scripts/Creative.zs file from the 1.6 pack version and it hasn't changed so it also affects 1.6.

#### Modpack version (Do not use "latest")
1.5

**Comment by NillerMedDild** [comment]
Woops, I'll get that fixed asap :)
