### ISSUE TITLE
Crafting table not craftable in AE2 molecular assembler

### ISSUE THREAD

**Issue by Owis54** [NillerMedDild/Enigmatica2ExpertSkyblock#133]
Issue Description
Crafting table not craftable in AE2 molecular assembler
#### Modpack version (Do not use "latest")
1.6
#### Crash Report
no crash was caused 
[pastebin/gist/etc link here]

**Comment by GuntherDW** [comment]
Can't reproduce, I've crafted plenty of crafting tables in the molecular assembler?
Check your logs though, if you setup the recipe to allow substitutions it might be the same issue SevTech is having.
https://github.com/DarkPacks/SevTech-Ages/issues/3161

**Comment by NillerMedDild** [comment]
As Gunther says, please supply your latest.log :)

**Comment by Owis54** [comment]
[latest.log](https://github.com/Discomanco/Enigmatica2ExpertSkyblock/files/2413765/latest.log)
i think this is it if not tell me and i while try to figure out what it is

**Comment by NillerMedDild** [comment]
It is indeed related, it doesn't look like it'll be fixed :/
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3575
