### ISSUE TITLE
Wrong "achievement text" when claiming "Creative Modifier" loot.

### ISSUE THREAD

**Issue by GuntherDW** [NillerMedDild/Enigmatica2ExpertSkyblock#137]
#### Issue Description
Most (well, all of the ones I have completed so far, so I can't be 100% certain) of the "bragging rights" quests also show up publicly ingame that you've completed said quest.
The "advertisement" for the "Creative Modifier" quest however tells others that you've completed the "Creative Mill" quest instead.
This looks like either a copy paste error or an oversight? The questbook is correct, it's just the "advertisement" ingame that's incorrect.

![Chat and hotbar](https://i.imgur.com/X6jHSrN.png)

#### Modpack version (Do not use "latest")
1.6

**Comment by NillerMedDild** [comment]
Thank you for the report :)
