### ISSUE TITLE
Quantum Entangloporter quest text inconsistency

### ISSUE THREAD

**Issue by GuntherDW** [NillerMedDild/Enigmatica2ExpertSkyblock#138]
#### Issue Description

The questbook text seems to have an inconsistency when talking about the Quantum Entangloporter.
On the left it states that the quantum entangloporter can transfer 16 M RF/t.

While technically (almost) correct, the (default) config value of 16M refers to 16M J - Mekanism' own energy system - per tick.

Also according to the config shipped with the pack (or default), J -> RF is 1:0.4.
So it can transfer 16M J/t, or 4M RF/t.
But this also is a constraint per network. So let's say you have 8 M RF/t. You'll have to make 4 quantum entangloporters and 2 networks to be able to fully transfer those RF's.

This can quickly become a nuisance because stuff like the industrial turbine from Mekanism generates upwards of 30 or 40M RF/t from a single fusion reactor and still have a lot of steam to spare.
As well as other constructions being seriously buffed in terms of power usage like a void miner or an rftools dimension builder. Having to create a network for each of them can quickly become a nuisance.

We personally (significantly) upped the limit on our server, but the main issue is that the questbook is talking about RF, while the mekanism config is talking about J(oules), its own energy network.
Setting general.EnergyType in the Mekanism config only really applies to what is shown in UI's by default, not what it speaks internally.

![questbook text](https://i.imgur.com/YtLHE68.png)

#### Modpack version (Do not use "latest")
1.6

**Comment by NillerMedDild** [comment]
It can transfer 6.4MRF/t, 1 Joule is 2.5 RF.

However I agree it should be raised, working on it now :)

**Comment by NillerMedDild** [comment]
Increased to 25.6MRF/t.

**Comment by GuntherDW** [comment]
Ah looks like my calculations were a bit off there then.
Thanks for correcting me and that's a bit better already :).

We personally just made it near unlimited, judging by the dragon heart recipe cost and it being one of the only inter-world and long distance high RF throughput blocks, but 25.6MRF/t per channel is a big improvement already.

**Comment by NillerMedDild** [comment]
I believe Integrated Dynamics/tunnels has unlimited wireless transfer :)
