### ISSUE TITLE
cardboard boxes either bugged or trigger bugs

### ISSUE THREAD

**Issue by Seegras** [NillerMedDild/Enigmatica2ExpertSkyblock#139]
## Thank you for helping us improve. #####

**Issue Description**

* If you pick up an Industrialcraft block with a cardboard box and unwrap it again, it looses its texture and is now named "invalid", and inert. 

* If you put a cardboard box containing an invalid block (as above) or a spawner into an AE2 system, it can't be retrieved anymore. Empty cardboard boxes can be retrieved. 

**Modpack version (Do not use "latest")**

1.5

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Bad bot!

Thank you for the report, I'll get the first of the issues fixed asap :)
