### ISSUE TITLE
Server world gen issue

### ISSUE THREAD

**Issue by R3kandH4V0k** [NillerMedDild/Enigmatica2ExpertSkyblock#144]
Good evening, I was trying to set up the  pack on my server so my friend and I can play together, I started the server and it generated a regular overworld. I tried regenerating a new world with the world setting as Void but it doesn't do anything. is there something im missing, or doing wrong?

**Comment by R3kandH4V0k** [comment]
really? I followed the template and your bot closed the issue?

**Comment by NillerMedDild** [comment]
The setting used for a void world is 'voidworld' I believe. The server files downloaded through Curseforge are set to it by default. I will edit the Curseforge description to reflect that :)

I understand your frustration with the close issue bot, but you did not follow the template - it tells you to include modpack version and logs, just to name a few things. 

It's there to save me time, as maintaining a modpack is actually pretty time consuming.

Please let me know if this resolves your issue.

**Comment by NillerMedDild** [comment]
Rude bot xD
