### ISSUE TITLE
Add Mod: ME Capability Adapter

### ISSUE THREAD

**Issue by Arudarin** [NillerMedDild/Enigmatica2ExpertSkyblock#145]
**Is your feature request related to a problem? Please describe.**
I was going to make a Compact Machines setup earlier today, and realized that you need a separate mod for Applied Energistics 2 capability!

**Describe the solution you'd like**
I would like https://minecraft.curseforge.com/projects/capability-adapter to be added

**Comment by NillerMedDild** [comment]
I will add it, thank you for the request.

**Comment by NillerMedDild** [comment]
move to enigmatica2

**Comment by Arudarin** [comment]
>move to enigmatica2

Excuse me?

**Comment by NillerMedDild** [comment]
That's supposed to be a command that moves this issue to the Enigmatica2 repository, but it didn't work :P

**Comment by NillerMedDild** [comment]
More bot fiddling, I hope these notifications aren't too annoying.

/move to enigmatica2
/move to enigmatica2expert

**Comment by Arudarin** [comment]
It's fine, fiddle all you want lol

**Comment by Arudarin** [comment]
Question, but as referenced here, https://github.com/ExtraCells/ExtraCells2/issues/578 , if you were to upgrade ae2 to rv6-stable (Implements native fluids), it would break ExtraCells2. Would you like to upgrade ae2 and remove ExtraCells2, or refrain from upgrading ae2?

**Comment by NillerMedDild** [comment]
I would prefer to update AE2 and remove EC2, but I haven't tested it yet, so nothing's set in stone yet :)

**Comment by p455w0rd** [comment]
I would recommend removing EC2..at least until i get EC3 out (which has most of the fluid stuff removed)

**Comment by Arudarin** [comment]
I see.
Would that require a world reset Niller?

**Comment by Arudarin** [comment]
Also, the cyanite recipe for the Fission Reactor does not oredict yellorium to uranium

**Comment by Arudarin** [comment]
You forgot to include it in the changelog
