### ISSUE TITLE
Environmental Tech's Void Ore Miner T6 Power Issues

### ISSUE THREAD

**Issue by Fatcow007** [NillerMedDild/Enigmatica2ExpertSkyblock#153]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Environmental Tech's void ore miner tier 6 has an issue with power comsumption.
Its maximum input required for miner (with full speed modifiers) is near 1.0^8 RF, but its config makes its buffer size stay at 1.0^7 RF.
This results in machine not being able to accept any power when its required input exceeds the buffer size, so basically we can't run T6 miner at full speed.

Increasing the buffer size fixes the problem for my case.

**Modpack version (Do not use "latest")**

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
I'll slab two zeros on it, thank you for the well-written report :)
