### ISSUE TITLE
Information tab inaccurate

### ISSUE THREAD

**Issue by ClassixX** [NillerMedDild/Enigmatica2ExpertSkyblock#154]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

The information tabs for Beryllium, Rhodochrosite and Fluorite are inaccurate, they state that they are only obtainable with the Mettallurgic Infuser. This is not the case. The Rock Crusher can make the crushed version of those items.

**Modpack version (Do not use "latest")**

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
I forgot to remove that, thank you for the reminder :D

**Comment by ClassixX** [comment]
Remove what? The information or the Rock Crusher recipes?

**Comment by NillerMedDild** [comment]
The information.
