### ISSUE TITLE
Zirconium/Crushed Quartz Recipe Broken

### ISSUE THREAD

**Issue by CLL692** [NillerMedDild/Enigmatica2ExpertSkyblock#155]
**Issue Description**

The Zirconium Recipe states, that it needs Crushed Quartz but there is no recipe for Crushed Quartz

**Modpack version (Do not use "latest")**
1.7

**Logs**

n/a

**Screenshots**

https://imgur.com/a/jLvh9XW

**Additional context**

I'm pretty sure the problem is Crushed Quartz. I had a recipe for Nether Quartz -> Crushed quartz but currently it gives Nether Quartz Dust instead of Crushed Quartz

**Comment by DasKashi** [comment]
You should be able to get Zirconium Dust via the Diorite recipe of NuclearCrafts Rockcrusher.
Since ActuallyAdditions' Crushed Quartz isn't even searchable in JEI, the non-working recipe you mentioned might actually be intended.

**Comment by NillerMedDild** [comment]
It is only obtainable through the Rock Crusher as of v1.8, thank you for the report :)
