### ISSUE TITLE
Smart Combustion controllers are absolutely out of control

### ISSUE THREAD

**Issue by ClassixX** [NillerMedDild/Enigmatica2ExpertSkyblock#160]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Using multiple Smart Combustion controllers in a single mutliblock greatly increases the output.
ie: I throw in 64 Cobble and 24 Blaze powder. Instead of 1 stack of Netherrack, I got 7.
This works with all combustion recipes, including Dark and Light Matter.

**Modpack version (Do not use "latest")**

1.7

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
It's supposed to yield 64 Netherrack but you got 7? That sounds like a decrease to me? :P

**Comment by ClassixX** [comment]
I meant 7 stacks
