### ISSUE TITLE
Missing Mekanism Recipes

### ISSUE THREAD

**Issue by Mighty0verlord** [NillerMedDild/Enigmatica2ExpertSkyblock#164]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**

Are Mekanism Gas and Liquid tanks uncraftable? There is no recipe and it kind stops the progress of the game.

**Modpack Version**

Enginamatica 2 Expert SkyBlock version 1.8

**Additional Context**

**Comment by NillerMedDild** [comment]
Yes they are, I'm looking for the cause.

**Comment by Mighty0verlord** [comment]
thanks for the quick response

**Comment by NillerMedDild** [comment]
Anything from Mekanism with the word Basic in it has no recipe, what the actual ****

**Comment by NillerMedDild** [comment]
Reported to be caused by CraftTweaker update.

**Comment by NillerMedDild** [comment]
https://github.com/CraftTweaker/CraftTweaker/issues/634
