### ISSUE TITLE
Environmental tech items not dropping.

### ISSUE THREAD

**Issue by MyNameBeMrRandom** [NillerMedDild/Enigmatica2ExpertSkyblock#167]
When destroying items from environmental tech they do not drop, there is a bug report on the [environmental tech](https://github.com/ValkyrieofNight/EnvironmentalTech/issues/157) github which says ValkyrieLib should be updated to 2.0.17.3 to fix this issue

**Modpack version**
1.8

**Comment by NillerMedDild** [comment]
... Update the modpack, I already did update ValkyrieLib
