### ISSUE TITLE
Add Mod: Plethora

### ISSUE THREAD

**Issue by Arudarin** [NillerMedDild/Enigmatica2ExpertSkyblock#173]
**Is your feature request related to a problem? Please describe.**
I wish to create a ComputerCraft autostock system that interfaces with AE2.
**Describe the solution you'd like**
Adding the describe mods.

**Comment by NillerMedDild** [comment]
I'm afraid the user basis is simply too small to warrant such a big addition of mods.

**Comment by NillerMedDild** [comment]
I'll have a look then :)

**Comment by NillerMedDild** [comment]
Those mods aren't available for 1.12.2

**Comment by NillerMedDild** [comment]
No that's alright, thanks though :)

**Comment by NillerMedDild** [comment]
Accepted!
