### ISSUE TITLE
Charged Draconium Block uncraftable

### ISSUE THREAD

**Issue by cpreh** [NillerMedDild/Enigmatica2ExpertSkyblock#176]
Modpack version 1.9b.

Charged Draconium blocks are uncraftable because they require 10M RF/t but in 
extendedcrafting.cfg combination_crafting.energy_capacity is set to 5M RF.
I can confirm that increasing this number (I tried 50M RF) works.

**Comment by freundlich** [comment]
Sorry, I didn't realize that this was already covered by the other issue. Yes, I tried crafting it with normal configs (where the internal buffer is 5M RF) and that didn't work. It said something like "not enough RF", although I fed it plenty of RF using an Energy Pylon from Draconic Evolution. I then changed the internal buffer size as mentioned and that immediately made it work without changing anything of my setup.

**Comment by NillerMedDild** [comment]
No worries :)

Hm, that doesn't sound good, I hope other recipes are fine.
