### ISSUE TITLE
Cable Anchors

### ISSUE THREAD

**Issue by bluesamoth** [NillerMedDild/Enigmatica2ExpertSkyblock#178]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description*
Quartz and Certus Quartz cutting knife are no long crafting cable anchors after the intial craft (once the knife takes damage). Tried to craft using normal crafting bence and AE2 crafting terminal and neither work.

**Modpack version (Do not use "latest")**
1.9b

**Screenshots**
https://imgur.com/a/nvbcwyj

**Comment by NillerMedDild** [comment]
Thank you for the report, it has been reported to the appropriate mod developer :)
