### ISSUE TITLE
Broken Quest Book and World Spawn blocks replaced

### ISSUE THREAD

**Issue by UnicoDios** [NillerMedDild/Enigmatica2ExpertSkyblock#183]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Had a power outage while playing causing computer to shut down. When able to get back on and reload world the quest book was completed deleted (no quests at all in the book) and it replaced all blocks at the default spawn with the default spawn blocks (tree + grass blocks). 

**Modpack version (Do not use "latest")**
1.9b

**Logs**
Entire log since computer restarted. First logged into world in 3rd from last log, exited and reloaded once to see if it would resolve problem, 3rd time (in last log) is after copying betterquesting folder from most recent backup.

https://hastebin.com/jizereyefo.md
https://hastebin.com/axasohojic.md
https://hastebin.com/giwowenuna.md
https://hastebin.com/fagituhatu.sql
https://hastebin.com/uliwuladod.md
https://hastebin.com/ocurinevax.md
https://hastebin.com/nugamolehu.md
https://hastebin.com/pekomuzewe.sql

https://hastebin.com/wilafogigi.md
https://hastebin.com/owabebemij.sql
https://hastebin.com/igemehoxen.http

**Screenshots**

Did not take any before fixing quest book myself. 

**Additional context**

I was able to fix the quest book by copying the betterquesting folder from most recent backup. It does not appear anything is missing/lost other than the replaced blocks at world spawn (thankfully I just moved that part of my storage).

**Comment by NillerMedDild** [comment]
I'm afraid I cannot prevent corruption in the event of a bad shutdown.
