### ISSUE TITLE
Crafting the Industrial Foregoing Plant Gatherer via ae2 crashes the game

### ISSUE THREAD

**Issue by RustyXXL** [NillerMedDild/Enigmatica2ExpertSkyblock#187]
I tried to let AE2 craft the Plant Gatherer. Doing so crashes the game.
The Issue is most likely to be caused by the modified Iron Axe and or Iron Hoe, according to yueh.
When AE2 crashes that way, the only way to save the affected world is to edit the save externally to stop the crafting.

Modpack version: 1.8b

https://pastebin.com/raw/SfehSmgZ

There is an open issue for this crash on the AE2 Github:
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3768

**Comment by NillerMedDild** [comment]
Can you reproduce the bug without Tool Progression?

Thanks for taking the time to investigate this issue so thoroughly, and for reporting it :)

**Comment by RustyXXL** [comment]
Tool Progression is not in Enigmatica 2 Expert Skyblock, as far as I can tell. The only thing I found editing the hoe was the Tools.zs.
I tried removing the line changing the durability, but that didn't change anything. The tooltip is still changed, so there has to be something else.
I also did pretty much narrow it down to the iron hoe, as I can't even put it in the ae system, and if I try I have to restart the game for AE to start working again.

Also I can't craft with Crafting tables anymore. This might be unrelated, but as soon as I have a crafting table in a pattern all patterns requiring that recipe won't craft. But no crash or something like that. I'm also sure it worked at some point, as I have a bunch of crafting cards in my system and I'm pretty sure I didn't craft those by hand. Again this might be related or not, I'm really not sure, and I worked around that by having a crafter always have a bunch of crafting tables available for the system...

**Comment by NillerMedDild** [comment]
Oh right, d'oh.

Would you mind testing if it works if you delete the `Tooltips.zs` script?

The Crafting Table bug is a known issue with Tinkers' Construct advancements I believe, turning advancements off should fix it, but I don't know if I'm willing to do that :/

**Comment by RustyXXL** [comment]
Sorry, my son is here the next few days, and I'll probably won't get to to much testing.
I did find the tooltips.zs and removed the iron hoe from it.
I also tried removing cyclic from the pack, as I've read cyclic being mentioned by another one related to this crash.
Both didn't change anything. I didn't try to remove the scripts itself, though.
It also seems to be strange that only the hoe would be the problem, if it was related to these scripts. Other tools don't seem to cause any problems.

**Comment by NillerMedDild** [comment]
In that case, I'm afraid the problem is not on my end. Thanks again for your testing :)

**Comment by freundlich** [comment]
I just tried to craft the Farming Station from EnderIO in AE2 and it crashed the game too. The server is now unable to start. The crash report looks the same as the one posted in the AE2 issue:

https://pastebin.com/raw/7s9EgZpu

**Comment by RustyXXL** [comment]
It's most likely the supremium Hoe in that case, would be my guess.
You'll have to remove the Crafting units from the world with nbtexplorer, to save the world. possibly even the Controller itself.
After that you could verify if it is the hoe, by trying to manually craft one and putting it into the system.
If it is the hoe it won't go in. You might need to restart the server after that for the ae system to work again, but it shouldn't completly ccrash, if the problem is consistent with the iron hoe.

**Comment by RustyXXL** [comment]
I might have an Idea what's causing the issue. I wrote somewhat more extensively n the ae2 github, but I think the cause might be the toolHoe oredict, or at least related to that, wherever that oredict entry comes from.

**Comment by RustyXXL** [comment]
I added

```
`
	val toolHoe = <ore:toolHoe>;
	for item in toolHoe.items {
		toolHoe.remove(item);
	}`
```
To the Oredict.zs, and it completly fixed the issue with the plant gatherer.
For some reason it only removes Vanilla tools from the Oredict, though, and my crafttweaker knowledge is not good enough to find out why. But it confirms, that the toolHoe oredict is indeed the problem in my case.

**Comment by NillerMedDild** [comment]
Well done! I will add that to both E2E and E2ES aswell.

**Comment by RustyXXL** [comment]
Cool, keep in mind, though that with my fix the crash with the superium hoe in the enderio farming station will still occur. Maybe temporarily, until the problem is completly solved use the axe or shovel? Both have no oredict iirc.

**Comment by NillerMedDild** [comment]
Would you mind trying to check if this recipe still crashes?

# Farming Station
	recipes.remove(<enderio:block_farm_station>);
	recipes.addShapedMirrored("Farming Station", 
	<enderio:block_farm_station>, 
	[[<ore:ingotElectricalSteel>, <thermalfoundation:tool.hoe_platinum>.anyDamage(), <ore:ingotElectricalSteel>],
	[<ore:ingotElectricalSteel>, <enderio:item_material:1>, <ore:ingotElectricalSteel>], 
	[<ore:gearVibrant>, <thermalfoundation:tool.axe_platinum>.anyDamage(), <ore:gearVibrant>]]);

It goes in the `EnderIO.zs` file, overwriting line 157-163.

**Comment by NillerMedDild** [comment]
Nevermind, that didn't work.

**Comment by RustyXXL** [comment]
As I said before, the only hoes I was able to remove the oredict from were the vanilla hoes. Almost all other hoes still have the toolHoe oredict. The only ones that didn't have that were the avaritia and twilight forest ones. I'm not sure if twilight forest was originally in the pack or if I added it myself, because I always add it if it isn't in the pack ^^

So I didn't try the recipe yet, but I tested putting the platinum hoe in the system, just to make sure, and it won't go in if I try, so I'm pretty certain it would also crash.

I have no clue why that is, though. from my understanding the snippet above should take all hoes and remove the OreDict, and as such should completly solve the problem.

**Comment by NillerMedDild** [comment]
Interesting, I can put the hoe in just fine, and I don't crash either. I do however get a printed exception in the chat.

**Comment by RustyXXL** [comment]
That's quite interestin. I am currently playing with a modified version of the pack, but I did test it with an unmodified version of the pack with the same results. Did you update any mods or the forge version in your instance?

**Comment by NillerMedDild** [comment]
Alright, I can craft it without the oredict, I've changed the recipe for now.
