### ISSUE TITLE
Gear press mold isn't workin'...

### ISSUE THREAD

**Issue by delou2b** [NillerMedDild/Enigmatica2ExpertSkyblock#189]
When trying to put items in the metal press with the gear press mold active using a hopper, the materials aren't going in the press. As you can see in the screenshots, iron, diamond and tin are in the hopper and none of them are going in the press.

Version of the pack : Enigmatica 2: expert skyblock 1.9b

**Screenshots**

![image](https://user-images.githubusercontent.com/44098679/46885601-bee62d80-ce58-11e8-9988-afc80b0f6714.png)

![image](https://user-images.githubusercontent.com/44098679/46885681-fb198e00-ce58-11e8-9f92-58e350cf8937.png)

![image](https://user-images.githubusercontent.com/44098679/46885695-08cf1380-ce59-11e8-9180-6d5d389eeb4a.png)

**Comment by RustyXXL** [comment]
The issue is, that the hopper tries to insert 1 item at a time, but the press doesn't accept a single iron as a valid ingredient. It works fine with things that insert all 4 ingots at once, ie the ME Interface.
