### ISSUE TITLE
Add Mod: Thaumic Additions

### ISSUE THREAD

**Issue by Arudarin** [NillerMedDild/Enigmatica2ExpertSkyblock#191]
**Is your feature request related to a problem? Please describe.**
It would be pretty cool to have some more stuff in Thaumcraft, as at the moment it is mostly up until void metal.

**Describe the solution you'd like**
Add Thaumic Additions mod

**Comment by NillerMedDild** [comment]
I'm afraid the answer is no, atleast for now. It's simply too OP compared to "vanilla" Thaumcraft, and that amount of additional magic content would be very hard to balance. 

I appreciate the suggestion though, I have considered adding Thaumic Additions many times :)

**Comment by Arudarin** [comment]
Alright, would you like me to let you know of any new addons to TC6 that come around?

**Comment by Arudarin** [comment]
For example:
 -Thaumic Tinkerer
 -Thaumic Terminal
 -Thaumic Arcana

**Comment by NillerMedDild** [comment]
Nah that's alright, I check Curseforge for mod updates daily :)
