### ISSUE TITLE
Uranium to Cyanite in NuclearCraft Fission Reactor

### ISSUE THREAD

**Issue by Arudarin** [NillerMedDild/Enigmatica2ExpertSkyblock#193]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

In the Fusion Reactor, the recipe for yellorium -> cyanite does not oredict to IE uranium ingots.

**Modpack version (Do not use "latest")**

1.9a

**Screenshots**

**Additional context**

**Comment by Arudarin** [comment]
So, should we use Extreme Reactors instead (to create cyanite)?

**Comment by NillerMedDild** [comment]
Nah, both can be used now :)
