### ISSUE TITLE
Problem with Quests

### ISSUE THREAD

**Issue by Boyownik** [NillerMedDild/Enigmatica2ExpertSkyblock#201]
I've downloaded by Twitch app Enigmatica 2 Skyblock edition, but i have one problem. In "getting started" quests tab i don't see quests for skyblock edition, only for normal overworld. For example no diamond wand for building or dirt furnace which i saw on YT series.

**Modpack version (Do not use "latest")**
1.16

**Screenshots**

https://imgur.com/a/gjVe9JV

**Comment by NillerMedDild** [comment]
Try the command /bq_admin default load

**Comment by NillerMedDild** [comment]
Yep, I just confirmed this. Will fix asap.

**Comment by NillerMedDild** [comment]
Fixed, will push an update out immediately.

**Comment by NillerMedDild** [comment]
Alright update 1.16a is waiting for approval. Sorry for the inconvinience.
