### ISSUE TITLE
Recipe conflict - OpenBlocks Scaffolding and RandomThings Block of Sticks.

### ISSUE THREAD

**Issue by sapient** [NillerMedDild/Enigmatica2ExpertSkyblock#202]
**Issue Description**
OpenBlocks Scaffolding recipe conflicts with RandomThings Block of Sticks, making the Returning Block of Sticks un-craftable.

**Modpack version (Do not use "latest")**
1.10

**Logs**

**Screenshots**

**Additional context**

**Comment by tyler489** [comment]
You can use the forestry workbench to bypass recipy conflicts

**Comment by NillerMedDild** [comment]
I'll get that fixed, thanks for the report :)
