### ISSUE TITLE
Crash with mekanism solar in tinkers crafting table

### ISSUE THREAD

**Issue by bdudek** [NillerMedDild/Enigmatica2ExpertSkyblock#205]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

game crashes when putting mekanism solar panels in tinkers crafting table regular crafting table it works fine in

**Modpack version (1.16A)**

**Logs**

https://hastebin.com/pemusuxaya.rb

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Correct, I'm afraid there most likely won't be a fix :)
