### ISSUE TITLE
Why are infinity TiC tools slow?

### ISSUE THREAD

**Issue by Gimpler** [NillerMedDild/Enigmatica2ExpertSkyblock#206]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Infinity is likely the last material to be obtained during progression, but it has the mining speed of a vanilla diamond pickaxe.

**Modpack version (Do not use "latest")**

1.16a

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

https://cdn.discordapp.com/attachments/387715648526221313/503315602316984321/unknown.png

**Additional context**

Even cobalt and supremium are better and those are orders of magnitude easier to get

**Comment by tyler489** [comment]
Should probably  tweak the mining level on that too

**Comment by NillerMedDild** [comment]
That's weird, last I checked it had exceptional mining speed.

**Comment by NillerMedDild** [comment]
The Harvest Level is 14 already.

**Comment by tyler489** [comment]
That picture says 10

**Comment by NillerMedDild** [comment]
Oh right, this is skyblock. 10 is plenty.

**Comment by NillerMedDild** [comment]
bad bot.

**Comment by NillerMedDild** [comment]
https://github.com/Landmaster/PlusTiC/issues/230
