### ISSUE TITLE
Extra Utilities 2 Furnace voids items

### ISSUE THREAD

**Issue by rhestilow** [NillerMedDild/Enigmatica2ExpertSkyblock#207]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
If the Extra Utilities 2 Furnace is already processing an item, or is blocked on outputting an already-processed item because of a full output, additional items added to the furnace will simply be voided. This happens with shift-clicking, hoppers, and EnderIO item conduits, and possibly other item input methods as well.

I'm able to easily reproduce this issue in a creative test world. In my survival world, where some of my automation depends on backfilling items in machines, it caused me to lose a number of items.

**Modpack version (Do not use "latest")**

I first observed this in 1.16a. It seems to be a fairly recent and major regression. The furnaces did not do this in earlier versions, though I haven't tested to see which version introduced the bug.

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

Thank you!

**Comment by NillerMedDild** [comment]
Thank you for the report, I'll relay it to the Extra Utilities tracker asap :)

**Comment by Ricket** [comment]
https://github.com/rwtema/Extra-Utilities-2-Source/issues/208

**Comment by Ricket** [comment]
They are claiming it is still an issue in 1.9.7 but will be fixed in 1.9.8
