### ISSUE TITLE
Broken config for AdvancedRocketry

### ISSUE THREAD

**Issue by pksiazek** [NillerMedDild/Enigmatica2ExpertSkyblock#208]
**Issue Description**
During gameplay astroids doesn't have any ore (both in observatory and during mission).
After debuging code it seems that we have wrong configuration in config/advRocketry/asteroidConfig.xml

massVariability velues should be in range 0 and 1.

If it's higher (32 in our case) it can cause asteroid mass and number of ores negative.
Which leads to empty asteroid.

**Modpack version (Do not use "latest")**
1.41

**Comment by NillerMedDild** [comment]
Again thank you for investigating :D

**Comment by NillerMedDild** [comment]
I made an issue a few minutes before you :P
