### ISSUE TITLE
Black Quartz Compacting Drawer Compatibility

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica2ExpertSkyblock#210]
**Is your feature request related to a problem? Please describe.**
Unlike vanilla quartz, AA black quartz doesn't work with Storage Drawers' compacting drawers to convert between item and block form. It's a special rule for vanilla quartz built into Storage Drawers, but you can add more compacting drawer 'recipes' in the storage drawers cfg.

**Describe the solution you'd like**
Adding "actuallyadditions:block_misc:2, actuallyadditions:item_misc:5, 4" to the storage drawers cfg under S:compactingRules  would work

**Comment by NillerMedDild** [comment]
Have you tested your proposed solution?

**Comment by Rodg88** [comment]
Yep, it works:
![2018-10-25_21 08 49](https://user-images.githubusercontent.com/2611674/47493100-37f27580-d89a-11e8-8f3d-19dcee9c53f3.png)

**Comment by NillerMedDild** [comment]
Excellent, thank you.
