### ISSUE TITLE
Recipes not working.... Liquid IO circuit board,  Wireless Universal Terminal

### ISSUE THREAD

**Issue by Minecr4ck** [NillerMedDild/Enigmatica2ExpertSkyblock#211]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Can't make Liquid IO circuit board in Advanced Rocketry Precision Assembler, because the recipe calls for ExtraCells 1k fluid storage components.  The crafting recipe calls for AE 2 fluid storage. 
Recommend unlocking the ExtraCells 2 fluid storage recipes, as there are other recipes like the Wireless Universal Terminal that can't be upgraded to fluid scanning because it requires an ExCells fluid terminal item that can't be crafted.

**Modpack version (Do not use "latest")**
1.41

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Liquid IO Circuit Board recipe fixed, the other is an issue with ExtraCells - ExtraCells is in the progress of being rewritten, so it won't be fixed for a while
