### ISSUE TITLE
Acquisition of AS constellation papers

### ISSUE THREAD

**Issue by MorganSimic** [NillerMedDild/Enigmatica2ExpertSkyblock#212]
**Is your feature request related to a problem? Please describe.**
There was some talk in discord yesterday regarding the acquisition of constellation papers from AS. In its current form the only way to get them is from the deep dark, or craft them in the iridescent altar. This seems exceptionally complicated compared to non skyblock expert and can make AS quite a hassle to progress through.

**Describe the solution you'd like**
I suggest a way of obtaining constellation papers earlier through other means, e.g. some kind of crafting recipe. Some quick ideas include a very stable Thaumcraft infusion, Botania runic altar or maybe some Blood Magic stuff I have no idea of.

**Additional context**

**Comment by NillerMedDild** [comment]
Yes, this should be a thing. I'll add it :)
