### ISSUE TITLE
All ME Systems show as empty since 1.16a update.

### ISSUE THREAD

**Issue by TheFlash787** [NillerMedDild/Enigmatica2ExpertSkyblock#213]
**Issue Description**

Since we updated to `1.16a` from `1.9b`, **Everybody's** ME Systems have stopped working and 30% of the time, re-placing the controller works, although not all of the time. Has this been acknowledged before? Note, that all systems have the correct amount of power.

**Modpack version (Do not use "latest")**
`1.16a`

**Logs**
`N/A`
**Screenshots**
![](https://media.discordapp.net/attachments/447844825211863041/506110751182684170/unknown.png?width=1247&height=676)
![](https://cdn.discordapp.com/attachments/424971258124566538/506124141603323905/unknown.png)

**Comment by NillerMedDild** [comment]
Are the drives connected through P2P?

**Comment by TheFlash787** [comment]
Yep, all drives are connected through P2P, This has only started to happen since the moment we updated to the latest version.

It has been tested with a small system (literally one drive and controller) and it does the same.

**Comment by TheFlash787** [comment]
![](https://media.discordapp.net/attachments/424971258124566538/506163241735553047/unknown.png?width=1085&height=676)

**Comment by NillerMedDild** [comment]
Seems like there's not a lot of space left on the test system, does it still happen with another drive?

**Comment by NillerMedDild** [comment]
And can you replicate this in SP?

**Comment by TheFlash787** [comment]
After the automated restarts, the issue appears fixed. I will keep this open and respond when it happens again. If not, I'll close it. Thank you

**Comment by TheFlash787** [comment]
False alarm. An our or so in, same issue occurs.
![](https://files.modrealms.net/screenshots/19.44.22-28.10.18.png)

**Comment by SanMan911** [comment]
Just as an FYI (if it helps), our (Mine, kurre6163) ME in MP on the official Skyblock server is working perfectly fine and I am sure so is CaleCode's and FondleMyNoodle's, 2 other players on the server.
It freezes for a second or two while opening, but that's about it.

**Comment by NillerMedDild** [comment]
That does help, thank you. I think this bug is a product of skipping a few versions :/
