### ISSUE TITLE
Extra EU Generated from NuclearCraft Fission Reactor

### ISSUE THREAD

**Issue by Crindigo** [NillerMedDild/Enigmatica2ExpertSkyblock#216]
**Issue Description**

A reactor with multiple Fission Reactor Ports outputting EU will not divide the power properly.

In my case, I have a reactor generating 10,080 RF/t, which normally would output 630 EU/t as it divides by 16. If I only use one port, it correctly outputs 630 EU/t at voltage 4. If I use 4 ports, it outputs 512 EU/t @ voltage 3 from *each*, giving me a total of 2,048 EU/t as measured by an EU reader.

If I have 5 ports, each would output 128 EU/t @ voltage 2. I believe this is because the original 630 is divided by 5, giving 126 which fits under 128. With 4 ports it's ~157 so it rounds to the next tier at 512.

This is *probably* a NuclearCraft issue, but I know some configs were adjusted in this pack so I wanted to post here first.

**Modpack version (Do not use "latest")**

1.16a

**Logs**

**Screenshots**

https://imgur.com/a/Qg37ePK

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the report, this does indeed sound like a NuclearCraft issue. Will you repost this at https://github.com/turbodiesel4598/NuclearCraft/issues ? :)
