### ISSUE TITLE
Nuclearcraft cooling overflow

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica2ExpertSkyblock#221]
**Issue Description**
Large Nuclearcraft fission reactors, with active cooling, can overflow the cooling rate value, as it can go over 65535, and NC doesn't handle that. Apparently default NC config cooling values were "recently" updated, but not sure when, so the config may need a regen. Or if the heat values were intentionally boosted, they may need to just be set to normal. If the coolers are set to half efficiency that could maintain the 'difficulty' if that was the case

**Modpack version (Do not use "latest")**
1.16a, with a manually updated NC to 2.12f

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Rodg88** [comment]
Just an example:
![2018-11-10_18 28 55](https://user-images.githubusercontent.com/2611674/48308997-13014080-e5c4-11e8-8a61-fac4f8d61d2b.png)
![2018-11-10_18 29 13](https://user-images.githubusercontent.com/2611674/48308998-1399d700-e5c4-11e8-908b-1884fdc5e1d5.png)

**Comment by NillerMedDild** [comment]
The developer says it's just a GUI overflow, the Reactor should run just fine :)
