### ISSUE TITLE
Advanced Rocketry vaccum planets spawning mobs

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica2ExpertSkyblock#222]
**Issue Description**

I landed on Mars at night, and mobs were spawning everywhere, but then they all start suffocating. The moon doesn't have mob spawns. Not sure what options there are for controlling the mob spawns though. Or maybe Mars is meant to have an atmosphere but doesn't?

![2018-11-11_15 33 42](https://user-images.githubusercontent.com/2611674/48309131-65902c00-e5c7-11e8-891b-786f6e49c35f.png)

**Modpack version (Do not use "latest")**

1.16a, advanced rocketry still stock 1.16a version

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
My change did not resolve it, reported the issue: https://github.com/zmaster587/AdvancedRocketry/issues/1441

**Comment by MSandro** [comment]
When will this issue be solved?

**Comment by NillerMedDild** [comment]
I do not know.

**Comment by StefanTT** [comment]
How about the workaround MSandro mentioned in the upstream defect?  He installed Mobs Properties Randomness and gave the mobs space suits.

This remembers me on Galacticraft where the mobs also had cute glass block like space helmets - probably because of the same problem.

**Comment by NillerMedDild** [comment]
Fixed with In Control, no more mobs planet-side!
