### ISSUE TITLE
Lithium Manganese Dioxide EnderIO compat broken

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica2ExpertSkyblock#223]
**Issue Description**

You can't make Lithium Manganese Dioxide ingots in the Ender IO alloy smelter, it makes Magnesium Diboride ingots instead. Using the Nuclearcraft alloy smelter makes the correct ingots.

**Modpack version (Do not use "latest")**

1.16a

**Screenshots**
The correct recipe:
![2018-11-11_19 23 50](https://user-images.githubusercontent.com/2611674/48310769-65ecef00-e5e8-11e8-9d42-c8ae3a52fe71.png)
Same ingots in the EIO machine:
![2018-11-11_19 24 00](https://user-images.githubusercontent.com/2611674/48310771-6d13fd00-e5e8-11e8-99d3-2f4e2bb94cab.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Have you tested if this happens, or just checked JEI?

**Comment by LumberWizard** [comment]
Fixed, waiting for merge: https://github.com/SleepyTrousers/EnderIO/pull/4946

**Comment by tyler489** [comment]
Woops my bad
