### ISSUE TITLE
False Text after achieving Creative Modifier

### ISSUE THREAD

**Issue by KingFishQiu** [NillerMedDild/Enigmatica2ExpertSkyblock#228]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
It is not a big issue. But after i Made the creative modifier and claimed the reward, the text shows I have achieved creative Mill instead of creative modifier. There was a same report two months ago https://github.com/NillerMedDild/Enigmatica2ExpertSkyblock/issues/137 but the issue still exists, so I think it doesn't hurt to submit another report. 
![2018-11-15_19 46 09](https://user-images.githubusercontent.com/43681658/48568287-1708c780-e910-11e8-8091-1572e72a1896.png)
![2018-11-15_19 46 20](https://user-images.githubusercontent.com/43681658/48568299-1cfea880-e910-11e8-8811-2be22bc8f217.png)

**Modpack version (Do not use "latest")**
1.42a

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Have you used the `/bq_admin default load` command? I've fixed this once already, as you point out :)
