### ISSUE TITLE
Arcane Crafting Engine

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica2ExpertSkyblock#235]
**Is your feature request related to a problem? Please describe.**
Arcane crafting table recipes are un-automatable. The mechanisms at least would be nice to be able to autocraft.

**Describe the solution you'd like**
A Modular Machine based around an arcane crafting table would be great. While it wouldn't be able to use vis from the chunk, you could include vis batteries or crafted crystal clusters in the machine blueprint to simulate a vis useage system that would have little impact on vis anyway. The elemental crystals could be added to the normal inputs for the recipes too.

**Additional context**
I made a test blueprint as an example:
https://pastebin.com/NP171G4m

**Comment by NillerMedDild** [comment]
Very nice suggestion, and blueprint, I will add it :)

**Comment by NillerMedDild** [comment]
I must say that is one beautiful multiblock :D

**Comment by NillerMedDild** [comment]
I changed it a little, because I thought it was a bit too busy in the JEI preview.
![billede](https://user-images.githubusercontent.com/21295394/50311073-3b723980-04a4-11e9-9816-b241d4eeabef.png)
Are you okay with that?

**Comment by NillerMedDild** [comment]
Page 45 / 91 of Arcane Workbench done.

**Comment by chezpaul** [comment]
I have a question about this machine. In order to build it there are at least 2 elements, like the Vis Battery for example, that can only be crafted with this arcane machine. So I can't craft the Vis battery because I don't have a Arcane Machine yet. Apart from winning Vis Batteries as a reward when you claim something, is there another way to get them?

**Comment by NillerMedDild** [comment]
You need to unlock Thaumcraft recipes by getting the Thaumonomicon and doing the research. The Thaumcraft quest section tells you this :)

**Comment by giovanni-orciuolo** [comment]
Hello! Does this structure require Vis in the chunk to work?

**Comment by NillerMedDild** [comment]
It does not :)
