### ISSUE TITLE
Re-bound "betterquesting" keybind doesn't work, even with no other conflicting keys.

### ISSUE THREAD

**Issue by Lucidi** [NillerMedDild/Enigmatica2ExpertSkyblock#236]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
I re-bound the "Open Quests" key from betterquesting, from "grave" to "z" and the key doesn't work.
I have tried re-binding the veinminer key from backslash to grave and that works, so the issue only applies to the betterquesting "open quests" key.

**Modpack version (Do not use "latest")**
1.52

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**
https://imgur.com/a/83st1LZ

**Additional context**

**Comment by Lucidi** [comment]
I've replaced it with Shift+Z and it works fine now :)

**Comment by NillerMedDild** [comment]
Awesome :)
