### ISSUE TITLE
Remove Bibliocraft Armor Stands because of bugs

### ISSUE THREAD

**Issue by Selway00** [NillerMedDild/Enigmatica2ExpertSkyblock#241]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Bibliocraft armorstands cause rendering errors in the log.  The armor stand appears to visually render but is issuing the error provided in the github link below.  It appears that the issue is fixable by simply breaking and removing all armor stands. 

**Modpack version (Do not use "latest")**

1.16a

**Logs**
If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

https://pastebin.com/NQSJcwii  

**Screenshots**

**Additional context**

Also, it is possible it creates some mild level of chunk corruption as other mods that use custom texturing of blocks, (enderio painted blocks, storage drawers custom drawers, and architecture craft custom blocks) revert back to their base textures.  For instance, Enderio glow painted blocks show the pink/black texture, the storage drawers turn back into their framed version, architecturecraft blocks revert back to their ramps form.  Removing the armor stands, then relaunching the pack seems to allow the affected blocks to revert back to their custom textures.   The storage drawers do not appear to lose their contents either. 

Earlier, I found a post on the Bibliocraft Github referencing this issue and the author apparently confirming the issue.  However, for some reason, I am unable to find it there anymore.

**Comment by drakkensong21** [comment]
If it just causes counsel spam why disable them so other people that use them extensively lose them.

**Comment by Selway00** [comment]
> If it just causes counsel spam why disable them so other people that use them extensively lose them.

> If it just causes counsel spam why disable them so other people that use them extensively lose them.

Fair point.  The downside is the extremely large log files that are created (100s of megs.)  Other than that, I suppose 10s of thousands of generated error codes likely cause some performance issues.

**Comment by NillerMedDild** [comment]
I've reported this issue before, and have been unable to get it fixed I'm afraid. It has been known for years now :/

**Comment by NillerMedDild** [comment]
If there's even a chance of chunk corruption, I think the best approach would be to remove the Armor Stands entirely.

**Comment by Selway00** [comment]
Just a quick update if it is helpful.  I noticed that what might have caused the errors and chunk corruption was that I accidentally hit a dragon egg and it warped to an adjacent tile of the bibliocraft armor stand.  Subsequently, the error codes started and the other mods blocks with modified textures started having issues as well.  FYI.  Appreciate all your great work.

**Comment by NillerMedDild** [comment]
Alright, cool. Thank you :D
