### ISSUE TITLE
Compressed Stick no longer craftable.

### ISSUE THREAD

**Issue by SuperKael** [NillerMedDild/Enigmatica2ExpertSkyblock#246]
**Issue Description**

As of this version of the pack, the Compressed Stick from Sky Compression can no longer be crafted.

**Modpack version (Do not use "latest")**

Version 1.17

**Additional context**

It makes crafting compressed rock grinders and cutting knives a lot more convenient. It was craftable in the previous version... I can't be crafted anymore due to a recipe conflict with the "Block of Sticks" from Random Things.

**Comment by NillerMedDild** [comment]
Is the recipe gone, or the item itself?
