### ISSUE TITLE
Mekanism Machines Use Power Even When Idle

### ISSUE THREAD

**Issue by duckies789** [NillerMedDild/Enigmatica2ExpertSkyblock#247]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Many Mekanism machines (not sure if it applies to all of them) continue using power when they are idle (i.e. nothing is being processed and internal buffers are full).

**Modpack version (Do not use "latest")**

1.17

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by duckies789** [comment]
Thanks, Also just adding some more information for the purposes of replication. I was using a metallurgic infuser, crusher, enrichment chamber, and and energized smelter, connected to a basic energy cube via hardened fluxducts.

**Comment by NillerMedDild** [comment]
That helps a lot, thanks.

**Comment by Gimpler** [comment]
This is a Mekanism bug, I've seen it happen with energy conduits as well as universal cables.

What's odd is that the machine buffer itself never decreases, just the amount in the cables.

**Comment by duckies789** [comment]
I’m not sure that this issue is limited to mekanism as a similar issue occurred with my industrial foregoing rubber setup. A fluiduct connecting the tree exctractor to the latex processing unit continued to send liquid rubber even when the internal buffer of the latex processing unit was full and the machine was off. This resulted in that liquid rubber being voided, and basically the tree extractor never backstuffed with liquid rubber. 
This should probably be a separate issue but I feel like they might be connected so I’m posting it here.

**Comment by NillerMedDild** [comment]
I cannot reproduce this with the same setup.
