### ISSUE TITLE
My server will not start

### ISSUE THREAD

**Issue by kushmoneyp** [NillerMedDild/Enigmatica2ExpertSkyblock#251]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
I recently downloaded the server file and the modpack. The modpack plays fine in single player but I can not get the server start up. 

**Modpack version (Do not use "latest")**
1.17

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

[latest.log](https://github.com/NillerMedDild/Enigmatica2ExpertSkyblock/files/2659915/latest.log)

**Comment by NillerMedDild** [comment]
You need to fill out the issue template.

**Comment by kushmoneyp** [comment]
I filled out the issue template and attached the latest log because it exceeds the hastebin limit. Thank you

**Comment by NillerMedDild** [comment]
Thank you.
It seems something went wrong during worldgen, I think you should re-install it.

**Comment by kushmoneyp** [comment]
It was giving me the same error last night. I redownloaded and installed it this morning and no progress.

**Comment by NillerMedDild** [comment]
Alright, I'll see if I can reproduce it, just a sec.

**Comment by kushmoneyp** [comment]
Okay thank you so much. :)

**Comment by kushmoneyp** [comment]
Do you know when the problem will be resolved?

**Comment by NillerMedDild** [comment]
I do not, but I'm launching a test server right now.

**Comment by NillerMedDild** [comment]
I'm afraid I couldn't reproduce the issue. How did you set up the server?

**Comment by kushmoneyp** [comment]
I did not setup up the server at all. I simply just downloaded the zip file and ran the serverstart. I did not configure the ip or anything.

**Comment by NillerMedDild** [comment]
Did you extract the files from the zip?

**Comment by kushmoneyp** [comment]
Yes.

**Comment by kushmoneyp** [comment]
[latest.log](https://github.com/NillerMedDild/Enigmatica2ExpertSkyblock/files/2660024/latest.log)
 just reinstalled and crashed again.

**Comment by NillerMedDild** [comment]
Err.. The forge version is wrong. Somehow.

**Comment by NillerMedDild** [comment]
Where did you download it from?

**Comment by kushmoneyp** [comment]
I believe it automatically downloaded from the command prompt when I initially boot it up. Is there is a manual way to do it?

**Comment by NillerMedDild** [comment]
Where did you download the server files?

**Comment by kushmoneyp** [comment]
curse forge

**Comment by kushmoneyp** [comment]
https://minecraft.curseforge.com/projects/enigmatica-2-expert-skyblock

**Comment by NillerMedDild** [comment]
This one?
https://minecraft.curseforge.com/projects/enigmatica-2-expert-skyblock/files/2641710

**Comment by kushmoneyp** [comment]
I downloaded 1.18 version

**Comment by NillerMedDild** [comment]
There is no 1.18, where did you get that?

**Comment by kushmoneyp** [comment]
Currently trying 1.17

**Comment by NillerMedDild** [comment]
Please answer my question, where did you find a version 1.18?

**Comment by kushmoneyp** [comment]
https://minecraft.curseforge.com/projects/enigmatica-2-expert-skyblock/files/2624289

**Comment by NillerMedDild** [comment]
... Version 1.8? From October? Why would you pick that?

**Comment by kushmoneyp** [comment]
https://minecraft.curseforge.com/projects/enigmatica-2-expert-skyblock

on this page the only server pack download link is for 1.18. I believe that is what caused the confusion. I apologize. Thank you for your help.

**Comment by NillerMedDild** [comment]
Fair enough :) You're welcome.
