### ISSUE TITLE
Items randomly disappear, though are still there.

### ISSUE THREAD

**Issue by DragonmasterDJ** [NillerMedDild/Enigmatica2ExpertSkyblock#256]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

When Looking in almost any Inventory expect the players own, all items in it Vanish until the player clicks on a spot where an item is, this can be extremely annoying, especially for me since I just got started into thaumcraft (for the first time actually!) and theory requires the paper and scribing tools to be inserted!

**Modpack version (Do not use "latest")**

1.17

**Logs**

None needed (well if asked, not too sure if this is a log-worthy problem)

**Screenshots**

![buggg](https://user-images.githubusercontent.com/29170640/49939634-82ef4780-ff31-11e8-92e5-7a7951010a42.PNG)

**Additional context**

none!

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by DragonmasterDJ** [comment]
Thank you, this is currently being SUPER annoying for me so I am hoping theres a fix for this soon.

**Comment by MistahLight** [comment]
As a small contribution, this happens to me too when I have a TiCon smeltery (or part of one) in the same chunk as the machine/block whose interface I am accessing (happened with the Coke Oven and Blast Furnace from IE).

**Comment by NillerMedDild** [comment]
Would you please test if moving the Research Table away from the Smeltery helps, as @MistahLight suggests? :)
Thank you for the help MistahLight!

**Comment by DragonmasterDJ** [comment]
I decided to get rid of the smeltery since I'm going to move to a new modern style- platform i'm planning to build out, and it worked! though Its going to be hard to not have the smeltery. thank you so much!
