### ISSUE TITLE
Recipe Conflict

### ISSUE THREAD

**Issue by FruityPewps** [NillerMedDild/Enigmatica2ExpertSkyblock#257]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Recipe conflict with open blocks scaffolding and random things block of sticks and sky compression compressed sticks.

**Modpack version (Do not use "latest")**

v. 1.17

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

`#OpenBlocks Scaffolding / Random Things Block of Sticks# OpenBlocks Scaffolding / Random Things Block of Sticks recipes.remove(<randomthings:blockofsticks>); recipes.addShaped("Random Things Block of Sticks",  <randomthings:blockofsticks> * 8,  [[<ore:stickWood>, <ore:stickWood>, <ore:stickWood>], [<ore:stickWood>, <ore:stickWood>, <ore:stickWood>],  [<ore:stickWood>, <ore:stickWood>, <ore:stickWood>]]);`

Recipe conflicts with the 3x3 stick crafting for compressed sticks in Sky Compression.

**Comment by NillerMedDild** [comment]
Update

**Comment by FruityPewps** [comment]
My bad, I actually didn't see the beta release that was up that included this fix. :). Sorry about that.

**Comment by NillerMedDild** [comment]
No worries, I forgot I didn't mark it as release, sorry for the rude answer :)

**Comment by FruityPewps** [comment]
Hey, the recipe conflict for compressed sticks is actually still present in the 1.18 release (updated the pack today). Just popped on to test some stuff and noticed it. Reinstalled pack just to make sure I wasn't derping. Please let me know if I am indeed derping.

**Comment by NillerMedDild** [comment]
Err. Oh. I'll have a look.

**Comment by NillerMedDild** [comment]
Yeah I'm an idiot :P fixed!
