### ISSUE TITLE
Items that spawn in world sometimes delete themselves.

### ISSUE THREAD

**Issue by DragonmasterDJ** [NillerMedDild/Enigmatica2ExpertSkyblock#258]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Sometimes when using some machines / blocks that spawn items into the world they fail to spawn the items in the world. the best example I can show is the Mana pool. For some reason, this only happens with the alchemy catalyst under it.

**Modpack version (Do not use "latest")**

1.17

**Logs**

None needed. (unless asked. not too sure if this is a log-worthy problem.)

**Screenshots**

EXAMPLE 1 : A sapling, its meant to turn into a spruce sapling.
![example 2](https://user-images.githubusercontent.com/29170640/50002014-d5dd0380-fff2-11e8-9c3c-0fc153fc7586.png)

EXAMPLE 1 - afterwards: Once placed in, it doesn't create the end- result sapling.
![example 2 2](https://user-images.githubusercontent.com/29170640/50002058-fefd9400-fff2-11e8-913c-871e8d5b36d6.png)

EXAMPLE 2: I then tried a stack of saplings.
![example 1](https://user-images.githubusercontent.com/29170640/50002080-1177cd80-fff3-11e8-9662-c7caaf569d07.png)

example 2 - afterwards:
1/4 of the saplings were destroyed.
![example 1 2](https://user-images.githubusercontent.com/29170640/50002133-2fddc900-fff3-11e8-9056-6e5e109d807c.png)

Though, when doing it without the catalyst. it gives me back all the resources.
![example 3](https://user-images.githubusercontent.com/29170640/50002162-3ff5a880-fff3-11e8-8388-ae2058b4f296.png)
![example 3 2](https://user-images.githubusercontent.com/29170640/50002164-4126d580-fff3-11e8-8c34-1162ad824a4f.png)

**Additional context**
none!

**Comment by NillerMedDild** [comment]
Is this on a server or single-player?

**Comment by NillerMedDild** [comment]
Nicely spotted!

**Comment by DragonmasterDJ** [comment]
:I ....
I'm a idiot lol, thank you so much for spotting that out for me. I guess that's why I couldn't turn slimeballs into cacti either. thank you!
