### ISSUE TITLE
Actually Additions Worms despawning

### ISSUE THREAD

**Issue by MistahLight** [NillerMedDild/Enigmatica2ExpertSkyblock#259]
Issue description:
AA worms are randomly disappearing from the world after being used on a tilled block. It happens in both the Expert and the Expert Skyblock versions.

**Modpack version (Do not use "latest")**
1.17

**Logs**

Nothing in the logs

**Screenshots**

No screenies

**Additional context**

At first I'd thought this was happening due to chunk loading/unloading using FTB Utils, or maybe even because of using JourneyMap waypoints, but it happens even without using any of those functions. They aren't just turning invisible, the tilled land dries up and converts to dirt if no water/new worm is provided.

Thank you.

**Comment by NillerMedDild** [comment]
I'm afraid that's on purpose. They're set to only last 250 seconds.
