### ISSUE TITLE
Mechanical user wont sieve. 

### ISSUE THREAD

**Issue by DragonmasterDJ** [NillerMedDild/Enigmatica2ExpertSkyblock#260]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

When setting a mechanical user to place blocks into sieves AND sieve them nothing will hapen.

**Modpack version (Do not use "latest")**

1.17

**Logs**

None needed

**Screenshots**

![2018-12-16_01 35 45](https://user-images.githubusercontent.com/29170640/50044135-2b88dd00-00d3-11e9-9af0-c1619546e561.png)

![2018-12-16_01 35 47](https://user-images.githubusercontent.com/29170640/50044139-35aadb80-00d3-11e9-9a76-a6716a6569c9.png)

**Additional context**

I have tried the other options of the mechanical user, still no other option dose the job.

**Comment by NillerMedDild** [comment]
That's working as intended, you can use the autosieve.

**Comment by DragonmasterDJ** [comment]
ah ok my bad, I guess I was so used to this method of auto-sieving.
