### ISSUE TITLE
All Modular Machines recipes in JEI are broken.

### ISSUE THREAD

**Issue by SuperKael** [NillerMedDild/Enigmatica2ExpertSkyblock#263]
**Issue Description**

As of this latest version (1.18), all Modular Machines recipes are broken in JEI, and do not show. If you click "Show All Recipes" while looking at the uses for one of the machine blueprints, the game will crash, obviously because of the lack of recipes.

**Modpack version (Do not use "latest")**

Version 1.18

**Additional context**

The actual recipes still work, they just don't show in JEI. Additionally, it should be clarified that they were perfectly fine in the previous version, Version 1.17

**Comment by NillerMedDild** [comment]
Thank you for the report, the issue is known.
https://github.com/NillerMedDild/Enigmatica2Expert/issues/442

**Comment by SuperKael** [comment]
Oh ok, at least it's known :)
