### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by firez037** [NillerMedDild/Enigmatica2ExpertSkyblock#265]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**
Crashes while initializing CodeChicken Lib

**Modpack Version**
1.18
[crash-2018-12-20_20.41.35-client.txt](https://github.com/NillerMedDild/Enigmatica2ExpertSkyblock/files/2701180/crash-2018-12-20_20.41.35-client.txt)

**Additional Context**

**Comment by NillerMedDild** [comment]
Reinstall the modpack :)
