### ISSUE TITLE
Petal Apothecary is not crafting

### ISSUE THREAD

**Issue by Dieguinfinite** [NillerMedDild/Enigmatica2ExpertSkyblock#270]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Petal apothecary not crafting**

**1.18**

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

https://imgur.com/a/mv13gMJ

**Additional context**

So i tried crafting it on the night, on different chunks, with chiseled cobblestone, but it doesn´t work.

**Comment by drakkensong21** [comment]
Did you craft the table your self

**Comment by Dieguinfinite** [comment]
yes :(

**Comment by NillerMedDild** [comment]
Craft another Luminous Crafting Table and try again please :)

**Comment by NillerMedDild** [comment]
So.. did it work?
