### ISSUE TITLE
quests of all players lost

### ISSUE THREAD

**Issue by choum33** [NillerMedDild/Enigmatica2ExpertSkyblock#271]
Hello,

We have a enigmatica 2 expert skyblock server for 4 players for some weeks. The server is UP only when all players are available to keep cohesion between player and roleplay a little.
So server was restarted maybe 20 times without any issue.
Yesterday all started fine but all users lost their quests so:
- they had to do them again (recraft some things)
- they got again lot of loot chests and this unbalance the game...

Is there a way to be sure that will not happen again? (i have another server enigmatica 2 expert and i had not this issue there).

Modpack is still 1.17

Thanks ;)

**Comment by NillerMedDild** [comment]
There is no way to make sure it doesn't happen unfortunately, but you can just load a backup of the world/betterquesting folder when it does happen. Backups can be found in the backups folder, and the world/betterquesting folder swell.
