### ISSUE TITLE
Unable to Unlock Eldritch Tab/Craft Void Metal Ingot

### ISSUE THREAD

**Issue by Grobes** [NillerMedDild/Enigmatica2ExpertSkyblock#285]
## Thank you for helping us improve. ####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**
Unable to unlock thaumcraft research as unable to spawn cultists. This breaks progression with Infinity Ingot which requires Void Metal Ingot. 

**Modpack Version**
Current release as of 31/12/18

**Additional Context**
I have completed all available Thaumcraft research. I have scanned the Void Seeds, I have closed rifts, I have eaten enough Zombie Brains to get insane amounts of flux. Yet the Eldritch tab remains locked. This blocks crafting of Void Metal Ingots. 

To unlock I need to scan a Cultist Book +/- an actual cultists. They do not spawn on the overworld. There are no Thaumcraft Structures generating on other planets. None of the other planets seem to have a Vanilla Desert Biome or any biome that will generate the cultist portals. The killing of Eldritch Guardians from flux events (and in a spawner) does not drop the book required. 

I have asked in the discord but nobody seems to have progressed past this without cheating, and I cannot think of any other way to move forward. 

To fix, a recipe could be added to generate a cultist portal (it's an egg) or the cultist book. 

Many thanks.

**Comment by Grobes** [comment]
Me again. Slight issue. 

Crimson Cult book recipe worked well. It allows me to complete "The Crimson Rites" thaumcraft research which unlocked the research "Delving into the Eldritch" which opened the Eldritch Tab on completion.

However, "The Crimson Rites" research will only appear after you scan a member of the Crimson Cult (I think these are "Crimson Preator, Crimson Knight and Crimson Cleric). Scanning these opens the thaumcraft entry "The Crimson Cult". Scanning an Eldritch Guardian did not open "The Crimson Cult".

I do not think it is possible to encounter the Crimson Cult members with a void overworld, and using RFTools dimensions to build a desert dimension to allow portals to spawn would require void metal anyway,

Thaumcraft does add Spawn Eggs for all their mobs and the Portals if you want to make a recipe for those, or you may know another way to encounter the Cult.

Also in current Beta, in the recipe for Sand to Silicon in the crusher, the output has changed from AE2 Silicon to Nuclearcraft Silicon, not sure if intended. Same for SAG mill output.

Sorry to bother you again.

**Comment by NillerMedDild** [comment]
Oh damn, I'm sorry. I assumed the Crimson Rites would be enough, for some reason.
I'll be making a recipe for the Portal Spawn Egg. Thanks for the letting me know.

The Silicon thing is not intended, I'll look into it.

**Comment by NillerMedDild** [comment]
![billede](https://user-images.githubusercontent.com/21295394/50887352-41986d80-13f3-11e9-92c0-708309e8bc7e.png)

**Comment by blarghhh** [comment]
comment: still on skyblock 1.18. it is possible to obtain the cultist book and the cultist knights/clerics without these.

max warp, one of the warp events will spawn a portal.
