### ISSUE TITLE
Putting cardboard box on ic2 scanner breaks machine

### ISSUE THREAD

**Issue by FunkyMoneyMan** [NillerMedDild/Enigmatica2ExpertSkyblock#288]
## Thank you for helping us improve. #####

**Issue Description**
When putting a cardboard box on the ic2 scanner machine and then removing the cardboard box. The texture is removed and the machine cannot be picked up.

**Modpack version (Do not use "latest")**
1.47

**Logs**
No logs

**Screenshots**
It's the default purple and block texture.

**Additional context**
May be an issue with other ic2 machines.

**Comment by Grobes** [comment]
This is a long standing problem with IC2 machines and mechanism. Don't think the pack author will be able to fix.

**Comment by NillerMedDild** [comment]
Thanks for the report, and you're in the wrong issue tracker :P

**Comment by NillerMedDild** [comment]
IC2 Tile Entities should now be correctly blacklisted.
