### ISSUE TITLE
Thaumcraft 6 infernal furnace bonus outputing both Thaumcraft nuggets & Thermal foundation. Also Unidict fix not working.

### ISSUE THREAD

**Issue by skillrax** [NillerMedDild/Enigmatica2ExpertSkyblock#291]
In world where problem was first found with only thaumcraft nuggets, the infernal furnace has not been broken or replaced. The issue was tested again after patch and the thaumcraft nuggets were the sole output and were still unable to be crafted into ingots via 3x3 pattern. 

I then created new world and went through all the research* to reach the infernal furnace and tested again with silver ore. The silver ore produced nuggets from both Thermal foundation and Thaumcraft!*. Seemingly choosing randomly from either as the count was uneven between both. In this world the thaumcraft nuggets were also unable to be crafted into ingots using the 3x3 pattern that the thermal foundation nuggets had access to. 

Heres my /ct hand scan for Thaumcraft and Thermal foundation silver nuggets respectively. Similar results with copper and lead. 
-<thaumcraft:nugget3> 
-OreDict: "nuggetSilver"

-<thermalfoundation:material:194>
-OreDict: "nuggetSilver"

-* Tested with copper and lead also. Similar result. 
-** The config for cheatsheet in thaumcraft to skip research, does not show a cheatsheet in JEI as expected. Could be hidden or config not working. Just thought id mention because it was a hassle lol.

**Comment by NillerMedDild** [comment]
Well that's annoying, thanks for testing so thoroughly :)
I'm guessing I should have removed the Thaumcraft nuggets from the ore smelting, instead of the actual ore.

The cheatsheet is hidden, I use commands for granting research.

**Comment by NillerMedDild** [comment]
Alright, it should be fixed properly.
