### ISSUE TITLE
Spice of Life Carrot Edition Config

### ISSUE THREAD

**Issue by Brillik** [NillerMedDild/Enigmatica2ExpertSkyblock#295]
I was surprised to discover on my skyblock play-through that I had satisfied my desires for unique foods after eating my 25th food. Checking the solcarrot.cfg configs, I noticed that enigmatica 2:expert is setup to continue rewarding hearts for up to 600 foods, whereas the skyblock is only set to 25.  I realize that it's much harder to obtain all of pam's seeds in the skyblock, but I don't understand the reasoning behind gating the unique food hearts, as all of the seeds are available for purchase through the market.

**Describe the solution you'd like**
I'd like to be able to continue gaining hearts for eating unique foods, not just be satisfied with automating fish and chips and call it good.

**Comment by NillerMedDild** [comment]
This is not intentional.
