### ISSUE TITLE
Tiny Pile of Plutonium

### ISSUE THREAD

**Issue by JGuerndt** [NillerMedDild/Enigmatica2ExpertSkyblock#312]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Tiny Pile of Plutonium from IC2 found in Fire and Ice chest at dragon lair does not stack with Tiny Pile of Plutonium from other sources (Thermal Centrifuge/etc).

**Modpack version (Do not use "latest")**
1.46

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

While exploring, I've come back, placed the newly found Tiny Pile of Plutonium(s) in a Storage Drawer, then walked away, removed my hazmat suit, only to discover I still have the item(s) on me. They "disappear" from my inventory until I click in the position they were in, then they reappear. There is no OreDictionary entry for them, so that upgrade is useless for storage drawers (I tried anyway though). Even shift-clicking them to a plain vanilla chest will temporarily stack them together, but will separate as soon as you close the chest. All in all, it's not a major issue, but I have died a few times, lol

They will cross-craft together to make the Plutonium item though.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Wrong repo btw, moving it.
