### ISSUE TITLE
Reload quest completion messes up the book

### ISSUE THREAD

**Issue by fuj1n** [NillerMedDild/Enigmatica2ExpertSkyblock#314]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
When you complete the reload quest for the first time, it stays completed, and subsequent completions partially mess up the book. This can be solved by manually executing the reload command, and doesn't happen if you do that in the first place.

When this happens, some quests are marked as complete even though they're not, and after a reload allows the player to claim the rewards from future quests.

A workaround solution to this problem would be to remove the reload quest to avoid this problem in the future.

**Modpack version (Do not use "latest")**
v1.21

**Logs**
Every time the quests are reloaded through the book [this](https://gist.github.com/fuj1n/c94d70f7327c3bb32e38b9dc853f1424) shows up in the log.

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**
![image](https://user-images.githubusercontent.com/4004193/50940451-256cfd00-14d5-11e9-99d6-76e06f53b9b1.png)

![image](https://user-images.githubusercontent.com/4004193/50940470-3453af80-14d5-11e9-8935-5555d751239d.png)
Two quests broken and autocompleted in gates

![image](https://user-images.githubusercontent.com/4004193/50940492-41709e80-14d5-11e9-894b-b0ab071d6e7e.png)
The quests stay completed after fixing

**Additional context**

**Comment by NillerMedDild** [comment]
That's odd, I was certain I removed that quest a while ago.

**Comment by fuj1n** [comment]
That's very odd, I just ran the reload command again to make sure I am not just being silly, and the quest is still there

![image](https://user-images.githubusercontent.com/4004193/50953378-477f7300-1507-11e9-894e-2fe2647c1ee7.png)

**Comment by NillerMedDild** [comment]
Well shit :P Sorry about that.
