### ISSUE TITLE
Flux Networks - Change Flux Generation Due to Bug

### ISSUE THREAD

**Issue by Jaymus3** [NillerMedDild/Enigmatica2ExpertSkyblock#315]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
The mod Flux Networks currently has a duplication bug involving Me formation planes and an ME system with no actual storage, such as a network with an import bus connected to a chest importing redstone, or an ME interface receiving redstone.  The formation plane will infinitely export redstone, but the redstone will never disappear from the chest or ME interface.  Removing the redstone from the chest or interface stops the dupe.  This makes automating fluix crystals tricky if you like to use an all-ae2 setup.  Disabling the creation of flux from fire fixes the issue, but makes flux generation impossible.  Perhaps disable it and add a recipe for the flux?  It's really easy compared to the usability right now anyways, and a combination of ender tanks, ender chests, and flux networks makes entangloporters and dimensional transceivers pretty much useless.  A harder recipe for flux would balance things out nicely.

**Modpack version (Do not use "latest")**
1.2.0-1.2.1

**Logs**
N/a
If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**
Other places this issue is documented:
https://github.com/SonarSonic/Flux-Networks/issues/239
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3563

**Comment by NillerMedDild** [comment]
Good idea, I'll make a new recipe. Thanks!
