### ISSUE TITLE
Untextured Draconium Ore

### ISSUE THREAD

**Issue by Grobes** [NillerMedDild/Enigmatica2ExpertSkyblock#316]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Untextured Draconium Ore Block

**Modpack version (Do not use "latest")**
1.21

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**
Using the Mekanism Combiner to create Draconium Ore from 8 Dust will create a Draconium Ore Block with the default untextured visual. It still behaves as you would expect as I can use it to automate the draconic crystals for the elite crafting table. 

Not sure why this happens or if it can be fixed. Just letting you know.

**Comment by NillerMedDild** [comment]
Thank you for the report, I'm fairly certain I can fix it :)
