### ISSUE TITLE
Add Calculator Mod

### ISSUE THREAD

**Issue by temp1029** [NillerMedDild/Enigmatica2ExpertSkyblock#317]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Add the calculator mod

**Additional context**
Calculator mod adds a lot of fun features and is a nice compliment to the recently added flux networks. I’d like to request it be added to the pack (I didn’t see a prior request to throw my support behind).

https://minecraft.curseforge.com/projects/calculator

**Comment by NillerMedDild** [comment]
If Calculator was to be added it would have to be integrated into the progression line, and it's way too late in the development for that. Additionally, a large content mod would increase load time even more, which I would like to avoid.
