### ISSUE TITLE
Extra Cells Universal 

### ISSUE THREAD

**Issue by Salnex** [NillerMedDild/Enigmatica2ExpertSkyblock#333]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Shift clicking, or perhaps any means of putting the Extra Cells Wireless Universal Terminal into a bauble spot causes the game to crash. That player will then crash on connection

**Modpack version (Do not use "latest")**
1.21

**Logs**

https://gist.github.com/Salnex/d597c321d76b455fc3ac6f06cc7d7569

**Screenshots**

N/A

**Additional context**
Reproduced sucessfully.
In server environment.

**Comment by NillerMedDild** [comment]
Looks like I need to update the mod - which version is on 1.21? ^^'

**Comment by Bluexin** [comment]
I guess this is duped by #405, which was closed.
This is still an issue on 1.29e though, so long after the fix was submitted in dev :/

**Comment by NillerMedDild** [comment]
The item should not be obtainable, is it?

**Comment by Bluexin** [comment]
It doesn't show up in the jei list, but looking for usages on any wireless terminal makes a craft for it show up (said craft works).

**Comment by NillerMedDild** [comment]
Dammit. You'll just have to stop using it, the dev will probably not fix it.

**Comment by Bluexin** [comment]
Yeah I had to edit my player's data file to remove the item because it'd crash upon login (equipped in bauble slot)

**Comment by NillerMedDild** [comment]
Hopefully 1.31 will fix some of ExtraCells issues, here's hoping.
