### ISSUE TITLE
How to get lubricant?

### ISSUE THREAD

**Issue by AlpacaStorm** [NillerMedDild/Enigmatica2ExpertSkyblock#337]
I've made a space suit and try to go to lunar.Then i notice the suit needs tank from advanced rocketry to store O2 , which need lubricant and need crude oil which needs bedrock . I don't know where to find it and there is no quest about it.

**Comment by NillerMedDild** [comment]
You need to use the Pump Jack to get Crude Oil, I suggest you read the Engineer's Manual :)
