### ISSUE TITLE
Updated BetterQuesting

### ISSUE THREAD

**Issue by Sir-Will** [NillerMedDild/Enigmatica2ExpertSkyblock#352]
hey,

please update the BetterQuesting mod asap. The quests get reset everyday and this should be fixed in a newer version.

**Comment by NillerMedDild** [comment]
Are you using the command `/bq_admin default load` frequently?

**Comment by Sir-Will** [comment]
No. Enigmatica 2 Expert seems to be fine so far after the last BQ update.

**Comment by NillerMedDild** [comment]
Nice, I hope it lasts.
