### ISSUE TITLE
Unable to craft "Large Solar Panel" from Advanced Rocketry

### ISSUE THREAD

**Issue by Grobes** [NillerMedDild/Enigmatica2ExpertSkyblock#353]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Unable to craft "Large Solar Panel" from Advanced Rocketry

**Modpack version (Do not use "latest")**
1.22 (Beta)

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**
Since changing from 1.21 to 1.22 the Large Solar Panel is uncraftable. The recipe is 6 Large Solar Panels, making it a bit difficult to create!. This results in the Tier 5 Solar Array being uncraftable which makes a lot of creative items uncraftable.

Also is the only way to make your first Flux Core for the Flux Network mod meant to be grinding a Dimensional Transciever? If so it may benefit from a tooltip.

Thanks for the great work

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

Yes, the first Flux Core is meant to be from grinding a Dimensional Transceiver. I don't think it needs a tooltip to be honest :)

**Comment by NillerMedDild** [comment]
Reported the recipe issue here: https://github.com/zmaster587/AdvancedRocketry/issues/1493
