### ISSUE TITLE
SP World crashes on load.

### ISSUE THREAD

**Issue by Psyvana** [NillerMedDild/Enigmatica2ExpertSkyblock#354]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
World loads up only to crash before rendering anything. 

**Modpack version (Do not use "latest")**
1.2.1

**Logs**

https://gist.github.com/Psyvana/7ec17593b55fc4871007d4eff30fd66b

**Screenshots**

**Additional context**

Do I need to update my mcedit version? D:

**Comment by NillerMedDild** [comment]
Looks like you put a tile entity of some kind into your Dank/Null/ - You'll have to edit it out with NBTExplorer, or delete your player data. Removing the mod, loading the world and readding it would also do the trick.
