### ISSUE TITLE
Redstone Reception Coil Recipe

### ISSUE THREAD

**Issue by blarghhh** [NillerMedDild/Enigmatica2ExpertSkyblock#372]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Redstone reception coil crafting recipe shows able to be made in metallurgic infuser with redstone and gold. Doesn't appear to be working.

**Modpack version (Do not use "latest")**
1.21

**Logs**

N/A

**Screenshots**

![2019-01-29_20 43 54](https://user-images.githubusercontent.com/6789845/51910447-2d4ffb00-240a-11e9-95a8-32cc00553aa5.png)

**Additional context**

**Comment by NillerMedDild** [comment]
Look at the info JEI tab.
