### ISSUE TITLE
Can't Autocraft with AE2 Singularities

### ISSUE THREAD

**Issue by TemperedFool** [NillerMedDild/Enigmatica2ExpertSkyblock#378]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**
Trying to automate Anglesite production. Because the singularity used as the central ingredient is the exploded, paired variety, not only will EnderIO Impulse Hoppers not handle them (NBT/meta mismatch I assume), but AE2 pattern specifying them just lists them as "Missing" when multiple pairs are in stock.

**Modpack Version**
1.23

**Additional Context**
If this is intended as a super-challenge, requiring the use (probably) of ID/IT to automate, ignore me! Otherwise, maybe just use the un-entangled singularities? Exploding them automatically is pretty trivial, so doesn't seem like it's removing much challenge.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Rodg88** [comment]
I'd agree with just using un-entangled instead, or maybe use draconic infusion crafting with 2 un-entangled ones to make minetweaked NBT-free singularity?

**Comment by NillerMedDild** [comment]
You can use any pipe/filter that has fuzzy NBT detection. EnderIO Item Conduits with Advanced Item Filters for one.

**Comment by TemperedFool** [comment]
I can transport them just fine - if I drop the ingredients in a chest it crafts with my setup. The problem is AE2 won't send the ingredients via a crafting pattern - it just comes up saying "missing" when you request the craft.

**Comment by TemperedFool** [comment]
I did indeed use an EnderIO advanced item filter for the local transport part ^_^

**Comment by NillerMedDild** [comment]
Even with OD Substitutions enabled?

**Comment by TemperedFool** [comment]
Yeah - I'm assuming it's not an oredict issue, but some sort of meta/NBT? There's gotta be some sort of data to match the pairs together I assume.

**Comment by NillerMedDild** [comment]
The OD Substitution option also ignores NBT, which is why I thought it'd work.

**Comment by NillerMedDild** [comment]
Nevertheless, the Beniotite / Anglesite recipes should be considered very hard automation challenges :)

**Comment by TemperedFool** [comment]
Hehe fair; given that I can throw 4 ingredients in a chest and it crafts, I feel like I've generally got it, but wanted to report in case you wanted it auto-craftable. I'll retest later and make sure it's still not working (and wasn't AE2 being cranky previously)

**Comment by NillerMedDild** [comment]
Sounds good, thanks :)

**Comment by TemperedFool** [comment]
I figured out why substitution doesn't work for this - you can't turn substitution in for processing patterns! I have another solution for automating this, so no worries either way.

**Comment by NillerMedDild** [comment]
Oh right!

**Comment by TemperedFool** [comment]
Is completely solvable though; just craft 2 and make the singularities as part of the craft ^_^

**Comment by BanditSan** [comment]
> Is completely solvable though; just craft 2 and make the singularities as part of the craft ^_^

Wanna share how solvable? Cause i don't see any way it is possible to use QES as input in AE2 pattern. Only why i see this fixable is Anglesite recipe should use Singularity not Quantum Entangled Singularity

**Comment by TemperedFool** [comment]
Spoilers? I'll give a hint: don't send a QES, send the plain singularity, an Ender dust, and a Tiny TNT.

**Comment by BanditSan** [comment]
> Spoilers? I'll give a hint: don't send a QES, send the plain singularity, an Ender dust, and a Tiny TNT.

So more pointless direwire? Why recipe cannot be be just this? [Screenshot](https://cdn.discordapp.com/attachments/523335321069420555/550930412562808833/unknown.png)
Not like there is any noticable resource difference between Singularity and Quantum Entangled Singularity

**Comment by NillerMedDild** [comment]
Why can't the recipe just be 3 sticks?

The difference between the Singularity and QES is the crafting of the QES is significantly harder to automate.

**Comment by BanditSan** [comment]
Which part of QES significantly harder to automate? A bit inconvenient cause AE2 processing don't have ode-dict substitution mode, maybe.

**Comment by NillerMedDild** [comment]
The explosion part.

**Comment by BanditSan** [comment]
[Is This so hard to do?](https://cdn.discordapp.com/attachments/523335321069420555/550969194569531392/2019-03-01_11.10.24.png)

**Comment by NillerMedDild** [comment]
Nope, but it's an extra automation step. If it's so easy why are you complaining?
