### ISSUE TITLE
Lithium Battery Cell Recipe

### ISSUE THREAD

**Issue by GGothicRide** [NillerMedDild/Enigmatica2ExpertSkyblock#382]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

the 1.23 update broke the recipe and therfore the chain for lithium batteries

**Modpack version (Do not use "latest")**

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

![screenshot_755](https://user-images.githubusercontent.com/19910160/52255202-2415d100-28d7-11e9-8005-f177c014b488.png)

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Still broken somehow
/move e2e

**Comment by GGothicRide** [comment]
i appreciate you taking the time to look into this and being so quick about it, definitely better then most Authors who go months without updating or fixing issues

**Comment by NillerMedDild** [comment]
No problem :)

**Comment by NillerMedDild** [comment]
I'm going to revert the recipe and report to the NC dev, the battery is behaving weird :P

**Comment by NillerMedDild** [comment]
I was told that it's intentional.
