### ISSUE TITLE
Buff Advanced Generators Turbines, Nerf Fuel Efficiency

### ISSUE THREAD

**Issue by GGothicRide** [NillerMedDild/Enigmatica2ExpertSkyblock#388]
**Is your feature request related to a problem? Please describe.**

-- Currently i'm running 1 maxxed Enderium gas turbine from Advanced generators and its problem currently is that the max output with ethylene ( the best fuel source for it ) is 42,500 Rf/t and these are crazy expensive to build
![screenshot_756](https://user-images.githubusercontent.com/19910160/52331024-adeb9a00-29bc-11e9-8a70-ada4afcd50e3.png)

**Describe the solution you'd like**

-- as expensive as these are i feel that they need a serious boost in power production peak and use more fuel to make them fair for the boost currently on 3.8 ~ 4.1 mB/t this is crazy efficient and seriously OP for an "expert" pack

**Additional context**

**Comment by NillerMedDild** [comment]
I've been thinking about buffing them for a long time, I agree. I'll buff them and nerf fuel usage as you suggest.
