### ISSUE TITLE
Trophies

### ISSUE THREAD

**Issue by Brillik** [NillerMedDild/Enigmatica2ExpertSkyblock#390]
Suggestion: Add trophies for completing every available quest in a mod.

When I was playing Modern Skyblock 3, one of my favorite aspects about that pack was the trophies gained for completing an entire section of quests. I've tried to find what mod in particular that came from but outside of Better Questing, I'm not sure. I would not award trophies for unlocking a gate as MS3 did, only for completing the page.

I realize that the trophies in and of themselves are useless compared to some loot chest prizes, but when people come to visit my base, I'd like to show off the fact that I completely completed forestry, or IC2, or any of the other mods in this pack - especially since it's common to cherry pick through the mods and not really explore them to depth.

**Comment by NillerMedDild** [comment]
I like the idea of trophies a lot, but unfortunately we have no way of detecting whether a quest chapter is completed or not.

**Comment by Brillik** [comment]
Huh, makes me wonder how MS3 did it then.

**Comment by NillerMedDild** [comment]
MS3 is built on GameStages. Unlocking a chapter unlocks a gamestage, and gives you the trophy. There'd be no good way to do it in E2E

**Comment by Brillik** [comment]
While I certainly don't understand all the mechanics of Better Questing, wouldn't it be possible to have a hidden quest tied to all of the other quests on that page? Just as each quest has a completion succession in order to progress, this hidden final quest requires all of the other ones complete and when done theres a submit box to award the trophy?

**Comment by NillerMedDild** [comment]
Oh right, that would be an ok solution.

**Comment by NillerMedDild** [comment]
I do not have time to work on this.
