### ISSUE TITLE
Schematic of Modular Machines inaccurate

### ISSUE THREAD

**Issue by TemperedFool** [NillerMedDild/Enigmatica2ExpertSkyblock#393]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
If you use Schematica to make a schematic of a modular machine (Advanced Metalurigic Fabricator, Carpenter, Thermionic Fabricator, Arcane Crafting Engine), the schematic produced has all of the Modular Machines blocks (casings, controller, input/outputs) replaced with other blocks such as leaves or bee hives.

**Modpack version (Do not use "latest")**
1.23 E2:ES

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**
https://imgur.com/N8MhGLV

**Additional context**
I zipped the schematics I made and they're linked below:

https://www.dropbox.com/s/1jnt293qydyxpxe/E2E%20Modular%20Machine%20Schematics.zip?dl=0

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I do not have the time to investigate this, as it's not a problem with the modpack itself, sorry.
