### ISSUE TITLE
Shard of laputa quest cannot be finished

### ISSUE THREAD

**Issue by Zimon88** [NillerMedDild/Enigmatica2ExpertSkyblock#399]
**Question or Issue**

Shard of Laputa quest is not able to finish. It look like quest required item with NBT but without tags, when shard that came out from crafting dont have NBT those at all, at least to tooltips.

**Modpack Version**

1.23

**Additional Context**

Those are screenshoots with advanded tooltip enabled:
![2019-02-11_22 04 04](https://user-images.githubusercontent.com/180848/52593439-4369ac80-2e49-11e9-9dfc-e3edba06ffdd.png)
![2019-02-11_22 04 20](https://user-images.githubusercontent.com/180848/52593440-4369ac80-2e49-11e9-9e8a-fd3701c20dc0.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
