### ISSUE TITLE
Starlight infuser

### ISSUE THREAD

**Issue by Richardm182** [NillerMedDild/Enigmatica2ExpertSkyblock#403]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Starlight infuser not working - Ive broke the entire structure twice and replaced it - I don't have the chalice to place down because I need 2 resonating gems, made via the infuser, but I have a tank of starlight in place of that, ive tried having a light well in replace of it, and different types of tanks, still doesn't work - ive tried at night, at day still nothing. - I used the ingame schematic to build it for me. So blocks should all be correct.

**Modpack version (Do not use "latest")**
1.23

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**
![infuser](https://user-images.githubusercontent.com/47633888/52789991-56ed6100-305d-11e9-9e01-d4d8dee3d30d.PNG)

**Additional context**

**Comment by NillerMedDild** [comment]
Is there a block of laps under the altar block? :)

**Comment by Richardm182** [comment]
> Is there a block of lapis under the altar block? :)

Yes, there is

**Comment by NillerMedDild** [comment]
And you've tried removing the tanks and Crucible?

**Comment by DrTasslehoff** [comment]
Schematica recipe is missing the 12 marble (regular AS variant) that goes below the liquid starlight. Make sure you add those

**Comment by Richardm182** [comment]
Ive tried removing the tanks/lightwell - And yeah I placed the 12 marble under them too

**Comment by DrTasslehoff** [comment]
Have you been right-clicking with a resonating wand after placing the item on the infuser to activate it?

**Comment by Richardm182** [comment]
Yup - im not completely stupid ;)

**Comment by drakkensong21** [comment]
I have to ask are all the liquid starlight source blocks

**Comment by Richardm182** [comment]
> I have to ask are all the liquid starlight source blocks

Yes, yes they are, I double checked that myself as well. As I thought that was going to be the issue

**Comment by drakkensong21** [comment]
do you have blocks under the pillers?

**Comment by Richardm182** [comment]
Yes, engraved marble

**Comment by drakkensong21** [comment]
try removing them

**Comment by Richardm182** [comment]
Didn't work - just tried - but theyre apart of the structure, so I didn't expect that to work

**Comment by NillerMedDild** [comment]
Hmm. What about a server restart?

**Comment by TemperedFool** [comment]
Have you placed the right type of marble under the liquid starlight? Needs to be plain Astral marble, not raw marble. Unless you stole it from an altar it needs to be chiseled.

**Comment by Richardm182** [comment]
Server restarts automatically every 8 hours, so yes - hasn't seem to help, going to to do some more testing later

**Comment by Richardm182** [comment]
Seem to have figured it all out now, I don't know exactly what was wrong - But I rebuilt it again, and managed to get it working - I also got rid of the red bar on my iridescent altar (it still worked even when it showed)

**Comment by NillerMedDild** [comment]
Well awesome I guess :P
