### ISSUE TITLE
Buff Creative energy cell

### ISSUE THREAD

**Issue by Richardm182** [NillerMedDild/Enigmatica2ExpertSkyblock#418]
**Is your feature request related to a problem? Please describe.**

The recipe for the creative energy cell isn't the hardness, no but for that tier of item, with a max output of 600k rf/t i feel its not really worth making, until the point you're going to use it in the next recipe required. At the point of creating this, id imagine people have atleast over 5m rf/t generation to run the tier 6 ore miner. Energy phantom faces dont work with it, therefor the max output i could find, was 100k rf/t per side.

**Describe the solution you'd like**
Id like to see the energy output buffed, to many around 5m rf/t total (not 5m rf/t per side) as this would be near on par with a small fusion reactor from nuclear craft - which is far easier to make

**Additional context**

**Comment by NillerMedDild** [comment]
The problem is I've been unable to change the I/O of the Creative Energy Cell, and other creative energy sources produce billions of rf/t per side.

**Comment by Richardm182** [comment]
I don't think it's the input and output as such, when it's part of the 'hive' of cells, it still only generates 600k RF/t even if your pulling out of say all 12 sides on 1 advanced energy cell and 1 creative, and the only other creative source of power is the EU generator? And that'd be limited by mekanism ultimate pipes for transferring would it not?

**Comment by NillerMedDild** [comment]
Oh right, I forgot which cell we're using :P

**Comment by NillerMedDild** [comment]
Attempting to change it by altering `config/rftools/rftools.cfg` line 1369 from 4 to 20, meaning 500 KRF/t per side, if it works.

**Comment by Richardm182** [comment]
Will be atleast worth putting down in the world at that point, thanks in advance :)

**Comment by NillerMedDild** [comment]
It works!

**Comment by Richardm182** [comment]
Wooo, thanks for all your hard work, great pack btw :)

**Comment by NillerMedDild** [comment]
Thank you :D
