### ISSUE TITLE
Traveling Dimensions bug

### ISSUE THREAD

**Issue by Cyborgmas** [NillerMedDild/Enigmatica2ExpertSkyblock#427]
1.24, but also happened in 1.23

Probably

No crashes

So the bug is a major, it basically desyncs multiblocks and others when going to other dimensions like the space station and other planets. For example, the fusion reactor from mekanism shuts itself down randomly when I come back from space. All of the advanced rocketry machinery multiblock stop working, they have to be turned off and on again (even if they say they are on). Plus my growth accelerators don't work anymore, I have to break and replace them. To redo the bug i would say make a multiblock from Advanced rocketry hook it up with autocrafting from Ae, it should work then go into a dimension and come back try autocrafting again, it shouldn't work.

**Comment by NillerMedDild** [comment]
You're in single player right? I'm guessing relogging would fix this. I've had reports of similar issues many times, I'm unable to fix it.

**Comment by Cyborgmas** [comment]
Okay, It's just annoying getting the reactor back on and off. Still a great modpack though!

**Comment by NillerMedDild** [comment]
I know :( thanks!

**Comment by NillerMedDild** [comment]
I have tried to fix this many times, and frankly I give up.
