### ISSUE TITLE
Creative Cell

### ISSUE THREAD

**Issue by Richardm182** [NillerMedDild/Enigmatica2ExpertSkyblock#430]
**Modpack version**
1.24

**Can the issue be reproduced?**
Yes/no/unknown

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
Im not 100% sure if this intended, so please remove if so. But yes great the buff for the energy cell worked you can now extract 1m rf/t per side BUT the internal generation is 1m rf/t so you can't actually use all 6 sides and get 6m rf/t - You still only get 1m rf/t because the cell completely drains itself as it cant keep up with production

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Sorta intended, not much I can do about it except buff it even further.
