### ISSUE TITLE
Unrocognised option -D64

### ISSUE THREAD

**Issue by Littledevill** [NillerMedDild/Enigmatica2ExpertSkyblock#431]
**Modpack version**
1.24

**Can the issue be reproduced?**
yes by just downloading the modpacks server files

**Issue**
the issue is everytime i go to start the server it says unrecognized option -D64
Running Linux ubuntu 18.04 i believe

[https://imgur.com/j73CR7Q](url)

**Comment by NillerMedDild** [comment]
It's a parameter that makes sure 64-bit java is used, I guess that's invalid on Ubuntu. You can safely remove it yourself :)

**Comment by Littledevill** [comment]
i dont suppose you could lend a hand and let me know where the parameter is as i cant find it anywhere in the linux version only in the .bat file

**Comment by NillerMedDild** [comment]
I'll look into it asap, but I'm afraid I'll be away from my laptop most of the day.

**Comment by NillerMedDild** [comment]
`settings.cfg` line 6
