### ISSUE TITLE
Buff Environmental Tech Solar?

### ISSUE THREAD

**Issue by TemperedFool** [NillerMedDild/Enigmatica2ExpertSkyblock#432]
**Modpack version**
1.24
**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
T6 ET Solar seems to put out aprox. 4.4MRF/T; given the end-tier nature of them, and the fact that a easily-sustainable and easy-to-build T48 NC Fusion reactor puts out ~28MRF/T, this seems a bit underwhelming?

**Comment by NillerMedDild** [comment]
Agreed, but it's a bit tricky to only buff one Solar tier at a time.

**Comment by TemperedFool** [comment]
Hmm; for what it's worth, it's a total PITA to make T4 & T5 too ^_^

**Comment by NillerMedDild** [comment]
True :P I guess I'll buff them all.

**Comment by TemperedFool** [comment]
I mean, you could always nerf fusion, but I imagine that would make some folks a little cranky ^_^

**Comment by NillerMedDild** [comment]
I'd rather not :D

**Comment by DrTasslehoff** [comment]
Should be noted that apparently you have buffed values on the worldgen while most of the skyblock is default (ends up with t6 solar being just shy of 9.5m RF/t

**Comment by TemperedFool** [comment]
Even 9.5m is a little underwhelming, but obviously not quite as bad. For the radiation poisoning I suffered from the RTG fuel I want more ^_^
