### ISSUE TITLE
Update Astral Schematica schematics

### ISSUE THREAD

**Issue by TemperedFool** [NillerMedDild/Enigmatica2ExpertSkyblock#433]
**Modpack version**
1.24

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
The schematics for Astral need updating. Most pressing is the Starlight Infusion altar - it is missing the marble under the starlight, and should not have the chalice as it isn't compulsory.

Additionally, it seems like often you need to break/replace the centerpiece to get the schematics to work; maybe just leave the main block out of the schematics entirely?

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
I didn't make the schematics, and it doesn't look like the group who made them has updated. Do you happen to have fixed versions?

**Comment by TemperedFool** [comment]
No, but I bet I can make some! I'll get into my creative world when I have some spare time and make schematics off of working examples.

**Comment by NillerMedDild** [comment]
Thanks, I really appreciate it.

**Comment by TemperedFool** [comment]
Gah, keep forgetting to send this:

https://www.dropbox.com/s/lxicxrcic16zfew/Starlight%20Infusion%20Altar%20%28no%20infuser%29.schematic.zip?dl=0

That's a fixed schematic for the Infusion Altar that includes the marble below the starlight, and omits the chalice and the central infuser. Placement for the infuser is obvious due to the lapis, so I think this is the best way to make sure the multi block is recognized and forms.

**Comment by NillerMedDild** [comment]
Thank you! Your schematic has been added to all the Enigmaticas.
