### ISSUE TITLE
Thermal Expansion Coal Coke Block 

### ISSUE THREAD

**Issue by blarghhh** [NillerMedDild/Enigmatica2ExpertSkyblock#436]
**Modpack version**
1.24

**Can the issue be reproduced?**
Unknown

**Logs**
N/A

**Issue**
Block of Coal Coke from Thermal doesnt have a recipe to convert back to coal coke compared to IE's block of coal coke.

![2019-02-23_12 52 21](https://user-images.githubusercontent.com/6789845/53281835-26e34380-376a-11e9-8788-40cab87cf495.png)

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
