### ISSUE TITLE
Crash to Desktop

### ISSUE THREAD

**Issue by power-spike** [NillerMedDild/Enigmatica2ExpertSkyblock#437]
**Modpack version**
1.24

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/Ub3x9CPJ
https://pastebin.com/BnH83c19

**Issue**
Sitting on a Space station Orbiting Terra Nova currently. after about 30-60 seconds the client locks up, First time Crashed to Desktop. 
Second time - client just went white - console said server had shut down.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
This problem should be solved on AR's side - I hope 1.25 will fix it, if not I'll investigate further :)
