### ISSUE TITLE
Thaumcraft Research Table

### ISSUE THREAD

**Issue by greatmonkey** [NillerMedDild/Enigmatica2ExpertSkyblock#440]
**Modpack version**
1.24

**Can the issue be reproduced?**
unknown

**Logs**
none

**Issue**
Going thought Thaumcraft, I have gotten as far as I can without having done any research and now I cant go any further because the research table is not showing how to craft it.  I was able to make the scribing tools but nothing else.

If this is a feature request, feel free to delete the template.

**Comment by TemperedFool** [comment]
You need to make a table (search JEI for "@thaum table" and I believe either right click the scribing tools on it, or maybe throw Salis Mundis in it first.

**Comment by greatmonkey** [comment]
I have made all 2 tables that I can and try to throw Salis Mundis on them and it did not work.  JEI is also not showing me how to make the research table, nor is the Thaumcraft book.

**Comment by TemperedFool** [comment]
Did you try right-clicking with the scribing tools?

**Comment by greatmonkey** [comment]
OK....that worked, why is there nothing saying how to get the table?

**Comment by TemperedFool** [comment]
Pretty sure the Thaumanomicon tells you how to do it?

**Comment by NillerMedDild** [comment]
Yep..
