### ISSUE TITLE
Wrong NBT tags - Packets too big and/or unsupported

### ISSUE THREAD

**Issue by tim54000** [NillerMedDild/Enigmatica2ExpertSkyblock#441]
**Modpack version:** 1.24
**Forge version:** 14.23.5.2781
**MultiMC version:** 0.6.4
**Platform:** ManjaroLinux (4.14.91-1-MANJARO)

**Can the issue be reproduced?**
Unknown [Reproducible by some people]

**Logs**
lastest.log (2,6MB) : http://cloudflare-ipfs.com/ipfs/QmehAdQ4PLxMSwnDUHEKoumVnwtYBH5p2b1FsVGbZKKyxH

**Issue**
1.Connect to a server with the modpack.
2.Suicide on a surface (in order to create a grave).
3.Disconnect or repeat step 2 until you are disconnected with the following error : 
```
Internal Exception: io.netty.handler.codec.DecoderException:
java.lang.RuntimeException: Tried to read NBT tag that was too big: tried to allocate: 2097170bytes where max allowed: 2097152
```

**=>** You will then no longer be able to connect unless you delete your player files from the server world.
*The problem would therefore be related to tombstones and/or death lists*

**Comment by NillerMedDild** [comment]
Interesting issue! I guess TombManyGraves needs to clean up when writing to the player's data.

**Comment by NillerMedDild** [comment]
Does the size of the player data correspond to the size mentioned in the log?

**Comment by tim54000** [comment]
Not really, 9667 bytes only

**Comment by NillerMedDild** [comment]
Do you have time to confirm whether it grows significantly when a player dies? No worries if not ^^

**Comment by tim54000** [comment]
Sorry for the absence. 
The problem is not really time but rather that I can't host the server on my own and launch an additional client. I encountered this bug on a friend's server but I don't have access to his machine (which means I can't delete corrupted files myself without him), so he may be able to give you more information than I can (but he doesn't use GitHub).

Sorry to can not do more than report the bug.

*PS: However, I pass this issue on to my friend if he can help you =)*

**Comment by CrossElectronics** [comment]
I wonder if the mod [Bigger Packets Please](https://minecraft.curseforge.com/projects/bigger-packets-please?gameCategorySlug=mc-mods&projectID=309110) is going to work, since it says "Fight against 'Tried to read NBT tag that was too big' errors, too". Hope that this could help if the problem hasn't been solved.

**Comment by NillerMedDild** [comment]
I don't have time to investigate this further (as you have probably guessed) sorry.
