### ISSUE TITLE
Cardboard box and AE2

### ISSUE THREAD

**Issue by greatmonkey** [NillerMedDild/Enigmatica2ExpertSkyblock#444]
**Modpack version**
1.24

**Can the issue be reproduced?**
Yes
**Logs**
no logs but took a screen shoot.
https://i.imgur.com/FECrt8c.png

**Issue**
When putting a cardboard box that has block data in it, into your AE system you will not be able to remove from the any terminal.

Only way I did find to remove it out of the AE system was to hook an ME Export Bus up to a chest with a fuzzy card on it and then put tell it to look for any cardboard box that has block data in it.

**Comment by NillerMedDild** [comment]
That is a known issue, no fix yet :)

**Comment by NillerMedDild** [comment]
It doesn't look like this will get fixed, at least in 1.12.2.
