### ISSUE TITLE
Cosmic meatball crafting automation

### ISSUE THREAD

**Issue by superx3man** [NillerMedDild/Enigmatica2ExpertSkyblock#446]
**Modpack version**
1.24

**Can the issue be reproduced?**
Yes

**Issue**
Not really an issue, but we currently won't be able to automate cosmic meatball using applied energistics because of the protein bucket. The bucket remains in the crafting table and there is no way to get the bucket out of the table automatically. I propose on changing the recipe to consume the bucket as well.

**Comment by NillerMedDild** [comment]
Thanks for the report, I'll look into it :)

**Comment by NillerMedDild** [comment]
You can get the empty bucket out through the Automation Interface's option to spit out invalid items.
