### ISSUE TITLE
Astral Sorcery no recipes working

### ISSUE THREAD

**Issue by iwanami** [NillerMedDild/Enigmatica2ExpertSkyblock#450]
**Modpack version**
1.24

**Can the issue be reproduced?**
yes, created a new world and doesn't work there either

**Issue**
Astral Sorcery recipes not craftable. Gate has been unlocked, some thaumcraft has been crafted (crafting bench, crucible,  thaumometer) , Astral Tome recieved, but impossible to craft neither a resonating wand or a lumious table.  So I spawned them, and  I'm still unable to craft a lightwell. Both first crafts are made in a normal crafting bench.
Am I missing something quest-wise?
Thanks and  best regards,
Iwanami
 
wand:
![image](https://user-images.githubusercontent.com/685838/53680607-42a49780-3cde-11e9-8395-b3f0009722d9.png)

table:
![image](https://user-images.githubusercontent.com/685838/53680614-5b14b200-3cde-11e9-8f08-e81d7f92c048.png)

lightwell  (also doesn't work when moonlight bar is full):
![image](https://user-images.githubusercontent.com/685838/53680620-64058380-3cde-11e9-96d6-82da73c22800.png)

**Comment by DrTasslehoff** [comment]
Have you added or removed any mods? I'm imagining either that broke scripts or possibly when you updated/downloaded some scripts aren't set up correctly. The first two recipes work fine for me. Anything using the AS crafting tables needs the appropriate tier of knowledge unlocked so when you cheated the table in you cannot craft with it as that knowledge is unlocked when you craft the table in the first place.

**Comment by iwanami** [comment]
I disabled AE2 channels, but that's it

**Comment by NillerMedDild** [comment]
Yep, that's the cause.

**Comment by iwanami** [comment]
yes, fixed. thanks for the quick answer :)

**Comment by NillerMedDild** [comment]
Sure thing :)
