### ISSUE TITLE
Lan player not seeing all recipes

### ISSUE THREAD

**Issue by iwanami** [NillerMedDild/Enigmatica2ExpertSkyblock#451]
**Modpack version**
1.24

**Can the issue be reproduced?**
unknown, not tested

**Issue**
I'm localhosting  for my GF to join me. She doesn't see all recipes, but can still craft them when she uses the correct ones.  Mainly affects Forestry recipes, but some other stuff too (pistons come to mind)
Also, some alternative recipes do not work (see below)
forestry casing, screenshot is from my client. My GF sees only the second one
![image](https://user-images.githubusercontent.com/685838/53680705-5c92aa00-3cdf-11e9-9c3d-aaeadc778f08.png)

Second recipe does not work:
![image](https://user-images.githubusercontent.com/685838/53680718-92379300-3cdf-11e9-9beb-67494d26be38.png)

She has GUI auto-scaling, but changing it does not show more recipes.
Thanks and best regards,
Iwanami

**Comment by NillerMedDild** [comment]
I highly recommend not using LAN, it's a mess. That being said, it looks like she's missing the scripts folder, or you removed a mod.
