### ISSUE TITLE
All texture white

### ISSUE THREAD

**Issue by cris195** [NillerMedDild/Enigmatica2ExpertSkyblock#452]
**Modpack version**
1.24

**Can the issue be reproduced?**
unknown

**Logs**
https://www.dropbox.com/sh/w5fjz8tdp59z2ex/AACVbD76F_ers24L4jnSslqia?dl=0

**Issue**
I started playing this modpack about 1 week ago, I have about twenty hours of play, since I started playing I installed the optifine and other 2 or 3 mods that do not change the world ruining the modpack, and a resource pack ( faithful). until yesterday no problem, the modpack is beautiful! ... but this morning as soon as I opened the game I found almost all the white textures. looking on the internet I found that the problem could be the optifine, then I removed it and I also removed the resoucepack but nothing has changed. I tried to reinstall the package and insert my world and it works for a while but after the textures disappear again ... how can I solve? thank you
(if you understand little is because I'm using a translator)

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Textures turning white is usually a sign of an issue with your GPU. Try updating your drivers :)

**Comment by cris195** [comment]
thank you so much! you saved me :), I have to compliment you have created a beautiful modpack that is creating me a few problems! It's difficult but beautiful! can I ask you what is the mod that puts the durability of the armor on the bottom right? because it only appears once in a while for a few seconds and I would like to put it fixed. thank you

**Comment by NillerMedDild** [comment]
Thank you :D 

I can't remember to be honest, maybe Quark.

**Comment by TemperedFool** [comment]
Pretty sure that's right - not sure there are settings to make those permanent though.
