### ISSUE TITLE
compact machine not load

### ISSUE THREAD

**Issue by cris195** [NillerMedDild/Enigmatica2ExpertSkyblock#454]
**Modpack version**
1.24

**Can the issue be reproduced?**
unknown

**Logs**

**Issue**
when I leave the compact machines the block does not load, was it done on purpose? I have to load it or is it a problem of the mod? thank you

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
You need to chunkload it yourself afaik.
