### ISSUE TITLE
Integrated dynamics named cards

### ISSUE THREAD

**Issue by ScottDTA** [NillerMedDild/Enigmatica2ExpertSkyblock#468]
**Modpack version**
1.24

**Can the issue be reproduced?**

**Issue**
Integrated dynamics/tunnels not keeping labels on server restarts.  

Probably something screwing with world saving in server shut down, but not dug into it yet to see if I can isolate which mod is the issue.

**Comment by NillerMedDild** [comment]
I have a feeling this will be solved when I update the Integrated Dynamics mods, but we'll see :)

**Comment by NillerMedDild** [comment]
Should be fixed in the next update, but not 1.25 sadly.
https://minecraft.curseforge.com/projects/integrated-dynamics/files/2693691
