### ISSUE TITLE
unable to form precision assembler

### ISSUE THREAD

**Issue by greatmonkey** [NillerMedDild/Enigmatica2ExpertSkyblock#471]
**Modpack version**
1.25

**Can the issue be reproduced?**
Yes

**Logs**
n/a

**Issue**
After you put in all the blocks needed to form the precision assembler from advanced rocketry and right click the precision assembler block, a red X shows up.  I have try to remake this thing in a test world with different coils/motors blocks combinations and it still will not form.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by greatmonkey** [comment]
ok...so I found the issue.  Problem was i was placing the facing of the precision assembler block on the side with 3 x 3 of the muti-block structure when the facing needs to be facing the side 3 x 4 side..........

Sorry...

**Comment by NillerMedDild** [comment]
No worries :)
