### ISSUE TITLE
Buckets being voided

### ISSUE THREAD

**Issue by blarghhh** [NillerMedDild/Enigmatica2ExpertSkyblock#473]
**Modpack version**
1.24

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
If you use buckets to take out fluids from a Extra Utilities 2 drum by hand, once your inventory is full, the extra buckets will get voided as you continue to empty the drums.

Only Extra Utilities 2 drums are affected. Other tanks, eg. Thermal, mekanism, will cause you to drop the extra filled buckets.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Does this happen in version 1.25?

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
Can you please check if this issue occurs on version 1.25?

**Comment by blarghhh** [comment]
Tested in a superflat world in 1.25 in survival mode. still occurring.  though filling buckets from TE tanks have a weird interaction of filling up the armour slots also

**Comment by NillerMedDild** [comment]
Cool, thanks for checking.

**Comment by NillerMedDild** [comment]
I'm afraid there's no workaround to this afaik.
