### ISSUE TITLE
Advanced Thermionic Fabricator Ore-dict

### ISSUE THREAD

**Issue by blarghhh** [NillerMedDild/Enigmatica2ExpertSkyblock#476]
**Modpack version**
1.24

**Can the issue be reproduced?**
Unknown

**Logs**
N/A

**Issue**
The corner steel block pieces of the Advanced Thermionic Fabricator must be that from IE. It says "missing structure" if the TE version is used. and the TE version is the default produced when the steel is made from the ingot form in a crafting table.

![2019-04-07_11 41 00](https://user-images.githubusercontent.com/6789845/55678337-62a52780-592a-11e9-9cb0-014e252c9f6f.png)
![2019-04-07_11 40 45](https://user-images.githubusercontent.com/6789845/55678338-62a52780-592a-11e9-976b-b2024b2693b1.png)

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
It's intended :)
