### ISSUE TITLE
Tinker I/O bug

### ISSUE THREAD

**Issue by greatmonkey** [NillerMedDild/Enigmatica2ExpertSkyblock#477]
**Modpack version**
1.25

**Can the issue be reproduced?**
Yes

**Logs**
n/a

**Issue**
Two Issues:

1. Left clicking on the Smart Output from Tinker I/O removes the item like you are in creative mode when you are in survival mode.

2. Braking the Smart Output with the correct tool, if any upgrades are in, the upgrades will get voided but you still get the Smart Output block back.

**Comment by NillerMedDild** [comment]
I'm afraid the second issue probably will not be fixed, as the mod seems to be abandoned. The first issue will be fixed in 1.26 :)

**Comment by greatmonkey** [comment]
That sucks....it really is a nice add on to Tinkers' but thanks for the update!
