### ISSUE TITLE
EnderIO Limited Item Filters broken

### ISSUE THREAD

**Issue by TemperedFool** [NillerMedDild/Enigmatica2ExpertSkyblock#478]
**Modpack version**
1.25

**Can the issue be reproduced?**
Yes/

**Logs**
N/A, I think?

**Issue**
Title; I cannot specify more than one of a given item in a limited item filter. Tested in a freshly installed instance. Reloaded my 1.24 instance, where it works fine. The scroll wheel works as intended, but it seems like the max number of items is just 1.

Possibly due to the update to EIO 5.0.43? 1.24 is using EIO 5.0.40. Will downgrading EIO harm anything?

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
https://github.com/SleepyTrousers/EnderIO/issues/4800

**Comment by TemperedFool** [comment]
For what it's worth, it's not quite that issue, although i would assume it is a mod issue rather than a pack issue. In my issue, you can't set a limit of X, you can only set a limit of 1.

**Comment by NillerMedDild** [comment]
Myeah I know, but I'm thinking they're similar enough to be grouped at the very least.

**Comment by TemperedFool** [comment]
Probably ^_^

Knowing my luck, that issue is with the vacuum chest and not the filter though!

**Comment by NillerMedDild** [comment]
Do you have time to check if this also happens with only EnderIO + JEI?

**Comment by TemperedFool** [comment]
I think so - I'll try it tonight.

**Comment by TemperedFool** [comment]
And... tonight turned into a week later. Obviously testing with EnderCore too, same version of Forge - vanilla install otherwise. Same behavior. After that, I assume it's some sort of issue with this build of EnderIO.

**Comment by NillerMedDild** [comment]
Roger, thank you.

**Comment by NillerMedDild** [comment]
https://github.com/SleepyTrousers/EnderIO/issues/5111
