### ISSUE TITLE
Destabilized redstone ore - unfindble

### ISSUE THREAD

**Issue by greatmonkey** [NillerMedDild/Enigmatica2ExpertSkyblock#479]
**Modpack version**
1.25

**Can the issue be reproduced?**
Yes

**Logs**
n/a

**Issue**
I just unlock the space part about 2 days ago and have spent hours trying to find Destabilized redstone ore, with the digital miner and without it, vain mining away a lot of stone.  I have been to every plant I can see on my list and still unable to find it.  There is nothing in JEI telling you were to find the ore as well, only that it spawns on other planets.  I think the ore spawning for it is bugged at this point.

**Comment by NillerMedDild** [comment]
It only spawns on 5 planets, the JEI plugin that tells you which is currently bugged but will be fixed asap :) I'm hoping within a few hours.
