### ISSUE TITLE
Band of Mana quest not completing

### ISSUE THREAD

**Issue by Zarkov2** [NillerMedDild/Enigmatica2ExpertSkyblock#489]
**Modpack version**
1.24

**Can the issue be reproduced?**
Yes.

**Logs**
No crash.

**Issue**
The quest for creating a Botania Band of Mana can't be completed due to not detecting the crafted item.

I have tried both with and without stored mana in the ring. Using the "/bq_admin default load" quest doesn't solve it, or crafting a new item afterwards. Manually clicking detect / claim doesn't work. Not sure it if matters, but it is the only quest that remains unfinished in the quest book.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
