### ISSUE TITLE
Nether Crash

### ISSUE THREAD

**Issue by mitchngwen** [NillerMedDild/Enigmatica2ExpertSkyblock#495]
**Modpack version**
1.26

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/embed_js/sSZQ3E8h

**Issue**
Game crashes when going to the nether

**Comment by NillerMedDild** [comment]
It looks like I forgot to update Phosphor, I'll hotfix as soon as Thaumic JEI also updates.

**Comment by mitchngwen** [comment]
Should I roll back to the previous version until then?

**Comment by NillerMedDild** [comment]
I recommend updating the mod Phosphor, that'll fix it :)

**Comment by mitchngwen** [comment]
thank you very much! And we are enjoying your modpack!

**Comment by NillerMedDild** [comment]
You're welcome, and I'm glad you like it :D
