### ISSUE TITLE
CC: Tweaked Peripherals

### ISSUE THREAD

**Issue by ScottDTA** [NillerMedDild/Enigmatica2ExpertSkyblock#498]
1.27a

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
With change from ComputerCraft to CC: Tweaked
Wired peripherals are no longer remember their number on restarts(server, not tested SP yet)

Example
MONITOR_0 becomes MONITOR_1 on the next restart.  MONITOR_2 on the following restart and so on.  This will break some programs.

This bug is reported fixed in the latest version of CC: Tweaked that was released.

**Comment by NillerMedDild** [comment]
Ah dammit, sorry about that.

**Comment by NillerMedDild** [comment]
Reopening for visibility.
