### ISSUE TITLE
Dragon Egg

### ISSUE THREAD

**Issue by greatmonkey** [NillerMedDild/Enigmatica2ExpertSkyblock#500]
**Modpack version**
1.27a

**Can the issue be reproduced?**
Yes

**Logs**
n/a

**Issue**
The dragon egg can be  crafted using the Mystical Agradditions craft using 3 dragon egg chunks and using the recipe added in by you, using 4 dragonstone, 2 eggs, 2 dragon hearts.

**Comment by NillerMedDild** [comment]
That is intended, thank you for the report.
