### ISSUE TITLE
dragon heart craft

### ISSUE THREAD

**Issue by greatmonkey** [NillerMedDild/Enigmatica2ExpertSkyblock#501]
**Modpack version**
1.27a

Could you add an end game craft for the Dragon heart and maybe the dragon scale as well?

**Comment by NillerMedDild** [comment]
Do you mean recipes using those ingredients, or making them?

**Comment by greatmonkey** [comment]
Making them, thought I did just find out you can use UU matter to copy a dragon heart (it's not listed in NEI) but that possess is kinda slow.

**Comment by NillerMedDild** [comment]
No, there are several automatable ways of obtaining them.
