### ISSUE TITLE
EnderIO Limited Item filters don't work with "self feed"

### ISSUE THREAD

**Issue by pfmoore** [NillerMedDild/Enigmatica2ExpertSkyblock#503]
**Modpack version**
1.62

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
Connect an EnderIO item conduit to a block with separate "input" and "output" slots (for example, an RFTools crafter, which is what I used). The other end of the conduit does not need to be connected to anything. Set "Insert" and "Extract" to checked, both on green, with "Self Feed enabled" set on the extract. Set extract to always active.

Now, place something in the output slot of the crafter. It gets extracted and inserted into the insert slot.

Now, configure a limited item filter to allow one of the item you're placing in the crafter (it has to be one, because of #478 which may be related even though the symptoms are different). Add it to the "Insert" side of the conduit and place some items in the crafter again. This time, none get extracted or moved to the input slot of the crafter.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by HenryLoenwind** [comment]
Works as designed. You told the conduit that there can only be a maximum of one item in the machine, and one is in there.

BTW: There is no way to know if a any slot is an "input" or "output" slot. The only thing you could do is to try inserting/removing an item, if that succeeds that slot probably is output/input---and you now have an item you cannot remove/put back...

**Comment by NillerMedDild** [comment]
Thank you for the clarification.
