### ISSUE TITLE
Torch hack for other planets

### ISSUE THREAD

**Issue by xSparky911x** [NillerMedDild/Enigmatica2ExpertSkyblock#504]
**Modpack version**
1.27a

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
Being in space, torches don't work, and for good reason, nothing to burn. However if you have torches in your inventory and make the Automatic Torch from Cyclic it will place normal Minecraft torches that still work despite there being no oxygen to burn. Just a heads up, not sure if this is intended or matters. Maybe the Automatic Torch needs to be disabled if it can not be configured.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I don't have time to get this fixed I'm afraid.
