### ISSUE TITLE
JAOPCA needs update to support newest version of Sky Compression

### ISSUE THREAD

**Issue by ALD76** [NillerMedDild/Enigmatica2ExpertSkyblock#509]
**Modpack version**
1.29

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/pSzNu4F6

**Issue**
Latest version of Sky Compression needs an update version of JAOPCA to avoid crash on startup.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Thanks, I'll update asap :)

**Comment by NillerMedDild** [comment]
1.29b uploaded, sorry for the inconvinience.
