### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by Gount** [NillerMedDild/Enigmatica2ExpertSkyblock#515]
**Modpack version**
Enigmatica 2 Expert Skyblock 1.29e

**Can the issue be reproduced?**
Yes for me

**Issue**
The Quest "Claim this quest in order to reload quests and loot chests. It is repeatable." is not working for me. I ran a script and the icon is blueish, but i can not claim.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
That quest isn't meant to exist, can you please use the command "/bq_admin default load" and see if it gets removed?

**Comment by AndrzejBaran** [comment]
I have the same problem. Command "/bq_admin default load" doesn't change anything for me

**Comment by NillerMedDild** [comment]
And you have sufficient rights to use the command?

**Comment by AndrzejBaran** [comment]
Yes... I think. "Open to LAN" with "allow cheats" is enough? I'm getting information on chat that execution of command was successful

**Comment by NillerMedDild** [comment]
Yep that'll do it - sounds like a bug on my end :)
