### ISSUE TITLE
NuclearCraft fission reactor port doesn't properly import or export fuels

### ISSUE THREAD

**Issue by StrawberryIchigo** [NillerMedDild/Enigmatica2ExpertSkyblock#516]
**Modpack version**
Version 1.29e

**Can the issue be reproduced?**
Yes

**Issue**
Fission reactor ports on solid fuel NuclearCraft fission reactors don't connect to EnderIO item conduits, and Thermal Dynamics itemducts attach but do not extract spent nuclear fuel. Fission reactor ports are expected to enable nuclear fuel to be inserted and extracted. I fixed the issue by upgrading NuclearCraft from 2.16f to 2.17a.

**Comment by NillerMedDild** [comment]
Thanks for the info :)
