### ISSUE TITLE
Amber Duping

### ISSUE THREAD

**Issue by featsuperior94** [NillerMedDild/Enigmatica2ExpertSkyblock#518]
**Modpack version**
1.65d

**Can the issue be reproduced?**
Yes

![Capture](https://user-images.githubusercontent.com/51495376/61598027-b68c0180-abe5-11e9-9274-ddcba914f12b.PNG)

![Capture2](https://user-images.githubusercontent.com/51495376/61598029-bbe94c00-abe5-11e9-9942-e566cfe90c84.PNG)

**Issue**
When crafting an amber block it only takes 4 amber but when you put the amber block in the table it gives you 9 amber in return. this causes easy duplication of amber and I am trying to get it fixed

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Thanks for the report, I fixed this a while back but I guess it didn't take :P

**Comment by featsuperior94** [comment]
I also know this is in Enigmatica 2 expert not just the skyblock version
