### ISSUE TITLE
Enrichment Chamber quest incomplete

### ISSUE THREAD

**Issue by Bluexin** [NillerMedDild/Enigmatica2ExpertSkyblock#519]
**Modpack version**
E2ES 1.19e, on dedicated server

**Can the issue be reproduced?**
Yes (by all players on this server)

~~**Logs**
Input pastebin link to crash-report or latest log, if applicable~~

**Issue**
Seems similar to NillerMedDild/Enigmatica2Expert#938 and others, except it's still happening with latest version of the Skyblock pack (for us at least).
I checked the NBT for the one in the quest description, it's the same in both (`mekData:{}`).

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Vercci** [comment]
Can confirm it happens on the latest 1.30 version of E2ES that just came out. The same fix of ignorenbbt true that regular expert got should work here too, at least it did in single player (Quest #182 if it helps).

Admin completing the quest isn't an option for us on the server we're using.

**Comment by Bluexin** [comment]
Had the same issue on 1.29e with a lot of Mekanism machine quests too btw.

**Comment by Basedgod199** [comment]
This is still an issue in version 1.30

**Comment by tjsd** [comment]
Quest 182 Enrichment Chamber and Quest 183 Crusher in mekanism chapter both have this bug. Probably wrong block. Any chance for a skyblock update soon? :)

**Comment by NillerMedDild** [comment]
Very unlikely to be honest, I'm working on 1.14.4.

**Comment by tjsd** [comment]
a curtesy bugfix mod update release at least? :) This pack has been so much fun as of late. Been bored and put it up and we are 9 people playing it now. Good skyblocks (looking at you ozone 3) is so far between! :D

**Comment by NillerMedDild** [comment]
Copy the entire contents of [this page](https://gist.githubusercontent.com/NillerMedDild/1c0ec3edd9effb452a45856b4c85c063/raw/46169ccf2b746a68a997631bccbc56b171fd01cb/gistfile1.txt) into the `DefaultQuests.json` file located in the `config/betterquesting` folder. You need to do this on the server.

Then, run the command `/bq_admin default load`

**Comment by NillerMedDild** [comment]
Fixed in 1.31
