### ISSUE TITLE
Game crashes when starting game

### ISSUE THREAD

**Issue by StinkyVoet** [NillerMedDild/Enigmatica2ExpertSkyblock#520]
**Modpack version**
Version 1.30

**Can the issue be reproduced?**
Unknown

**Logs**
https://pastebin.com/DLMLWA5b

**Issue**
Game crashes when starting up, I figured out the Applied Energistics block façades and the dummy fluid item base are causing an issue.

**Comment by NillerMedDild** [comment]
Have you tried more than once? :) I believe this issue is caused by a rare event where items load out of order.

**Comment by StinkyVoet** [comment]
Yes, I have tried multiple times

**Comment by NillerMedDild** [comment]
I recommend re-installing in that case.

**Comment by StinkyVoet** [comment]
I will try that, thanks. I'll report back if the issue remains

**Comment by NillerMedDild** [comment]
Thanks, I'll close the issue for now :)
