### ISSUE TITLE
All Induction Cells from Mekanism have same capacity and Induction Matrix not working correctly

### ISSUE THREAD

**Issue by AndrzejBaran** [NillerMedDild/Enigmatica2ExpertSkyblock#521]
**Modpack version**
1.30

**Can the issue be reproduced?**
unknown

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
Can't find info if it's intentional so I think it's a bug or something. Basically, every tier of Induction Cell from Mekanism (except basic one) have the same value of capacity and that is 2,14GRF. I've looked into config and everything looks fine there (values are correct), but in JEI and after crafting it shows 2,14GRF. Tried reloading configs, relog etc. 

Also when I'm building Induction Matrix (as multiblock structure), when used 3 of ultimate cells, GUI of Matrix shows max capacity of 2,14GRF. Tried different shapes and providers. Nothing works. For a second I thought that this capacity is just visual, but after crafting charged draconium (requires 2GRF), theres only ~0,14GRF left, so It's real capacity.  

![screen](https://user-images.githubusercontent.com/29891264/63337750-cfe9b000-c341-11e9-8542-7ed9ae99cc84.jpg)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by AndrzejBaran** [comment]
One thing in my description is wrong, sorry I've noticed it right now. Graphical indicator shows correct amount of stored power (last screen in report), but only graphically (I've just had not enough power generation to see difference) text still shows 2.14GRF/2.14GRF. Summarizing: looks like it's just visual bug, and cells are working correctly
