### ISSUE TITLE
Draconium Crystal (for making Ultimate Crafting Table) Uncraftable

### ISSUE THREAD

**Issue by bunnyman14** [NillerMedDild/Enigmatica2ExpertSkyblock#522]
**Modpack version**
1.67
**Can the issue be reproduced?**
Yes

**Logs**
No crash

**Issue**
Mekanism's Chemical Dissolution Chamber does not accept Nuclearcraft Sulfuric acid, and Mekanism's Sulfuric Acid isn't pipable nor bucketable.
Dissolution Chamber also does not accept piping via EnderIO fluid Conduits or Thermal Expansion Fluiducts
Combined, this makes the Draconium Crystal completely impossible to obtain, and therefore impossible to complete the Ultimate Crafting table.
Is there something I'm missing?

![2019-08-31_15 36 05](https://user-images.githubusercontent.com/7276888/64068367-32299700-cc05-11e9-901a-e9757fad471f.png)
![2019-08-31_15 36 25](https://user-images.githubusercontent.com/7276888/64068368-32299700-cc05-11e9-8364-47ef94873725.png)
![2019-08-31_15 36 44](https://user-images.githubusercontent.com/7276888/64068369-32299700-cc05-11e9-91cd-01b13868426a.png)

**Comment by bunnyman14** [comment]
![2019-08-31_15 42 24](https://user-images.githubusercontent.com/7276888/64068423-f3481100-cc05-11e9-8b46-af0279e91d6d.png)
It should also be noted that there is no input config for the Dissolution Chamber

**Comment by NillerMedDild** [comment]
You need to supply it with gas, not liquid.

**Comment by bunnyman14** [comment]
![2019-08-31_18 40 53](https://user-images.githubusercontent.com/7276888/64069773-e552ba00-cc1e-11e9-9490-9f10bd34dbdd.png)
It'd be nice if there was a visible difference, such as tagging one as a gas.

**Comment by NillerMedDild** [comment]
Absolutely, sadly that isn't possible for liquids and gases.
