### ISSUE TITLE
Crashing - Electric Jetpack or Backpack

### ISSUE THREAD

**Issue by AgentMadelor** [NillerMedDild/Enigmatica2ExpertSkyblock#527]
**Modpack version**
1.30

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/HBuBYP6m

**Issue**
Have been playing skyblock for a while.  Just made an electric Jetpack and put it on and recently made a iron backpack and game has crashed repeatedly - have restarted a number of times and world loads but immediately crashed.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Delete the options.txt file :)
