### ISSUE TITLE
Weird Bug occurring after a few minutes of playing

### ISSUE THREAD

**Issue by Seriitas** [NillerMedDild/Enigmatica2ExpertSkyblock#528]
Enigmatica 2 Expert Skyblock
Version 1.30

**Issue**
https://gyazo.com/f9e9aa1472ba8322dff8bc39111b119d

Signs and other stuff floating around the world

**Comment by NillerMedDild** [comment]
Are you using Optifine and/or a Resource Pack?

**Comment by Seriitas** [comment]
I'm not using Optifine but I'm using a resource pack but my friend is using neither

**Comment by NillerMedDild** [comment]
Did you make any modifications to the pack? Update mods on your own perhaps?

**Comment by Seriitas** [comment]
I didnt add any new mod to the modpack, but I updated BetterQuesting and StandardExpansion

**Comment by NillerMedDild** [comment]
Please provide your latest.log so I can investigate further :)

**Comment by Seriitas** [comment]
[latest.log](https://github.com/NillerMedDild/Enigmatica2ExpertSkyblock/files/3852899/latest.log)

**Comment by NillerMedDild** [comment]
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments
