### ISSUE TITLE
Log error

### ISSUE THREAD

**Issue by AurelienGamings** [NillerMedDild/Enigmatica2ExpertSkyblock#530]
**Modpack version**
Enigmatica 2 Expert Skyblock 1.31b

**Issue**
SPAM log error

**Logs**
https://pastebin.com/QnbbDt2M

**Comment by NillerMedDild** [comment]
I would like the full log please :)

**Comment by AurelienGamings** [comment]
Hey thanks for the answer i have no more information i just have this message that spam the server console.

**Comment by NillerMedDild** [comment]
Err, alright. I can't really report this further without the server's latest log - context is pretty important.
