### ISSUE TITLE
Crash with EU2 and Random Patches

### ISSUE THREAD

**Issue by MCEventHorizon** [NillerMedDild/Enigmatica2ExpertSkyblock#532]
**Modpack version**
1.31b

**Issue**
Seems like Random Patches mod has some conflict with Extra Utilities' Auto User.

**Logs**
https://gist.github.com/MCEventHorizon/126a95ad0954b81eac5336698e9ae6cb

**Comment by NillerMedDild** [comment]
Thanks for the report, I relayed it to Random Patches :)

**Comment by NillerMedDild** [comment]
Would you mind updating to `RandomPatches 1.20.1.0` and see if that fixes it?

**Comment by MCEventHorizon** [comment]
It works with 1.20.1.0 version of the mod.

**Comment by NillerMedDild** [comment]
Thanks!
