### ISSUE TITLE
Random Delays and Random Crashes with no log.

### ISSUE THREAD

**Issue by Osprey4444** [NillerMedDild/Enigmatica2ExpertSkyblock#533]
**Modpack Version**
1.31b

**Issue**
Server Randomly Crashes with no Crash Log. Other players also have certain lag issues with interacting with items, chests and chats.

**Logs**
https://paste.ee/p/lsOow
Console Spammed with this also - https://i.imgur.com/qdDNjnM.png

**Comment by NillerMedDild** [comment]
I will need the server's latest log from a crash event. There's no crash in the log you supplied I'm afraid.
