### ISSUE TITLE
Caught exception from Astral Sorcery

### ISSUE THREAD

**Issue by WimStienstra** [NillerMedDild/Enigmatica2ExpertSkyblock#534]
**Modpack version**
Enigmatica 2 Expert Skyblock 1.31b Server

**Issue**
When I try and start the server it will output after some time the following log. It seems a problem with Astral Sorcery, but with a quick Google people report this problem with other mods conflicting with Astral Sorcery.

I hope someone can help me.

**Logs**
https://gist.github.com/WimStienstra/fc924d0a7d16895c599e9d7164de784c

**Comment by NillerMedDild** [comment]
You have allocated under 1GB of RAM, you need 6 or more.

**Comment by Discomanco** [comment]
6GB may be overkill for the server, but clearly 1GB is not enough given `Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded`.  
3GB should suffice

**Comment by WimStienstra** [comment]
Alright, thx!
