### ISSUE TITLE
Cinnabar into quicksilver

### ISSUE THREAD

**Issue by luca4389** [NillerMedDild/Enigmatica2ExpertSkyblock#535]
**Modpack version**
1.32

**Issue**
I noticed that the cinnabar (secondary output from pulverizing gold ore) can enter in the redstone furnace and smelt into quicksilver (from thaumcraft), the jei didn't show the recipe and the only one that should give that output would be smelting the cinnabar ore (from thaumcraft)

**Comment by NillerMedDild** [comment]
I think that's more of a feature than an issue to be honest :)
