### ISSUE TITLE
Cannot cast molten emerald into gemcast when playing on a server

### ISSUE THREAD

**Issue by urikkiru** [NillerMedDild/Enigmatica2ExpertSkyblock#537]
**Modpack version**
1.33

**Issue**
When playing on a server, if you have molten emerald in your Tinker's smeltery, you cannot cast the molten emerald into gem cast. The casting process will stop almost immediately, sputtering tiny amounts of molten emerald into the casting table. If you continue until you hit the full amount for a gem cast, it will sit there at 100% doing nothing. Sometimes the smeltery will 'suck' the molten emerald back into the smeltery.(Which is bizarre, and wreaks of some king of server/client sync issue)

This problem does *not* occur in a single player world.

I'm also not the first to report it, it was noted on the Sky Factory 4 bug tracker https://github.com/DarkPacks/SkyFactory-4/issues/708 but was closed because I believe it worked on single player for Darkosto.

**Comment by urikkiru** [comment]
This could not be reproduced after restarting the server on my side. Not sure what's going on there, but the server had been up about 5 days.

**Comment by NillerMedDild** [comment]
Were you in spawn chunks?

**Comment by urikkiru** [comment]
Hard to say, I was at the starting location the server put me on. Seems
unlikely though. Odd that restarting the server made the issue vanish.
