### ISSUE TITLE
no way to get olives to get bee attracter

### ISSUE THREAD

**Issue by HermitForge** [NillerMedDild/Enigmatica2ExpertSkyblock#539]
**Modpack version**
latest

**Issue**
need rustic olives to get bee attracter from sky resources 2, only way to get olives is from rustic olive trees, there is no way to get rustic olive trees and pams harvestcraft olives don't work for making rustic olive oil.  If there's a recipe for the bee attracter, than why is it impossible to get?

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
