### ISSUE TITLE
Dilithium oredict doesn't match Creative Powercell recipe

### ISSUE THREAD

**Issue by mikewk** [NillerMedDild/Enigmatica2ExpertSkyblock#541]
**Modpack version**
1.33

**Issue**
LibVulpes Dilithium Crystals oredict appears to have changed from "crystalDilithium" to "gemDilithium".  This caused some blank spots in the Creative Powercell craft as it's still referencing the old oredict. 

**Logs**
NA

**Comment by NillerMedDild** [comment]
Huh, I thought I fixed that in 1.33. Thanks for letting me know.

**Comment by NillerMedDild** [comment]
Fixed in development :)
