### ISSUE TITLE
currently no way to get into botania

### ISSUE THREAD

**Issue by HermitForge** [NillerMedDild/Enigmatica2ExpertSkyblock#542]
**Modpack version**
latest

**Issue**
No way to get mystical flower petals to get petal apothecary, only visible way to get them is from other planets, and that's locked behind advanced rocketry which is locked behind psi which is locked behind botania

**Comment by Discomanco** [comment]
Floral Fertilizer should be obtainable, which you can get from red and yellow dye with some bone meal

**Comment by HermitForge** [comment]
didn't think about that, but there's no information tab telling you that, and people wouldn't think about that, I personally forgot that existed

**Comment by Discomanco** [comment]
You are the first to make an issue about it, and haven't seen much mention of it (if any) on the Discord either.
I think it's safe to say this was a one-of ;)
