### ISSUE TITLE
v1.34a missing Super Sound Muffler: Revived Mod

### ISSUE THREAD

**Issue by kosievdmerwe** [NillerMedDild/Enigmatica2ExpertSkyblock#545]
**Modpack version**
1.34a in Twitch Client

**Issue**
When I update to 1.34a in the Twitch client, I don't have the "Super Sound Muffler: Revived" mod, which isn't mentioned as removed in the 1.34a version logs. Version 1.34 mentions switching from "Super Sound Muffler" to "Super Sound Muffler: Revived", so this feels like a mistake.

**Comment by NillerMedDild** [comment]
Yep it's definitely supposed to be there, I'll have a look, thanks :)

**Comment by NillerMedDild** [comment]
Fixed in 1.35, thanks!
