### ISSUE TITLE
Advanced Rocketry Casing Not Craftable

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica2ExpertSkyblock#546]
Reported by steveb1793 from Discord, looks like he was crafting it correctly.

**Comment by Blutkirsche** [comment]
Please type the correct name of the item, then i can check this.

I can't find "Rocketry Casing" ...

**Comment by NillerMedDild** [comment]
Machine Structure and/or Advanced Machine Structure. I'm thinking it must've been a local issue though, since we've only received 1 report of it.
