### ISSUE TITLE
Landing on Luna instead of Novus.

### ISSUE THREAD

**Issue by SquizyBanana** [NillerMedDild/Enigmatica2ExpertSkyblock#547]
1.34a

advanced rocketry: trying to land on planet Novus wil result in you landing on Luna instead (dim: Planet 113)

first 3 videos are me landing on Luna, the last one is confirming im not on Novus by checking if dilithium ore exists on Novus (it doesn't) the files where to big for github so here is the link to a google drive folder
videos :https://drive.google.com/drive/folders/1o08R1m2BV_Ccs42QXTQ3Uini9EIt05Z2?usp=sharing

**Comment by SquizyBanana** [comment]
so, what i think happens is that the Dilithium ore exists on most planets, but it only shows 4 of them in JEI, because i went to kepler XXXX18 and it has dilithium and the energized netherrack, so the bug is not landing on the wrong planet, but the dilitium dimention sectrion in JEI being incomplete

**Comment by NillerMedDild** [comment]
I'm afraid I don't have time to patch the Dilithium section of Just Enough Resources. The quests tell you where you can find space ores anyhow :)
