### ISSUE TITLE
sky resources combustion takes bucket when lava used as fuel

### ISSUE THREAD

**Issue by HermitForge** [NillerMedDild/Enigmatica2ExpertSkyblock#548]
**Modpack version**
1.35
**Issue**
when I tried to use a lava bucket as fuel in my combustion heater, it took the bucket instead of just emptying the bucket.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Not much we can do here I don't think, sorry.
