### ISSUE TITLE
server with plugins

### ISSUE THREAD

**Issue by GoodEvil-SCT** [NillerMedDild/Enigmatica2ExpertSkyblock#549]
**Modpack version**
1.35

**Issue**
I can't remake your server version of Enigmatica2: Expert Sky Block, for added some plugins on server. And I can't added sponge core on your server. How I can install plugins on your server core.
Please help.

**Comment by NillerMedDild** [comment]
My modpack is for Forge, and Forge does not support plugins. You're on your own with SpongeForge.
The modpack already contains server utilities, via the mod FTB Utilities.
