### ISSUE TITLE
Issues with trying to make a server

### ISSUE THREAD

**Issue by hesseldh** [NillerMedDild/Enigmatica2ExpertSkyblock#551]
**Modpack version**
Enigmatica 2 Expert Skyblock version 1.35

**Issue**
No clue why but I am unable to make a server for the pack, the server log says it stopped(possible crash) and then restarts, sorry if some Dutch words are in there, I am from the Netherlands

**Logs**
https://pastebin.com/1VNVYZF7

**Comment by NillerMedDild** [comment]
`**** FAILED TO BIND TO PORT!`

You have another server running using the same port, change the port number in the server.properties and portforward the new port number :)
