### ISSUE TITLE
Mekanism's Sufuric Acid Bucket not craftable

### ISSUE THREAD

**Issue by MCEventHorizon** [NillerMedDild/Enigmatica2ExpertSkyblock#553]
**Modpack version**
1.35

**Issue**
Even though you can get liquid sulfuric acid and put it in a tank, you can't use a bucket on a fluid container to get sulfuric acid bucket.

**Comment by NillerMedDild** [comment]
Why is this an issue, what do you need the Sulfuric Acid Bucket for? :)

**Comment by MCEventHorizon** [comment]
For Chemical Dissolution Chamber, I could also use the Nuclearcraft one but I already have the setup for Mekanism's Sulfuric Acid considering Chemical Dissolution Chamber already uses it.

**Comment by NillerMedDild** [comment]
Can't you use pipes to move it around? I don't really think this is a bug, I believe it's intended :)

**Comment by MCEventHorizon** [comment]
For some reason I didn't see this, like I said I need the acid bucket for crafting the Chem Dissolution Chamber.

**Comment by NillerMedDild** [comment]
What about placing the bucket in an Ender IO tank to fill it?

**Comment by MCEventHorizon** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/15619786/80691694-e4856700-8ad0-11ea-8674-932feebcccba.png)
Doesn't work. There's no recipe for the bucket.

**Comment by NillerMedDild** [comment]
Thanks, I'll see what I can do :)
