### ISSUE TITLE
Enigmatica 2 expert skyblock void crystal block doesn't get empowered

### ISSUE THREAD

**Issue by mataramosiki** [NillerMedDild/Enigmatica2ExpertSkyblock#554]
**Modpack version**
Input version here
1.35
**Issue**
Input short description of the issue here
the empowerer did not empower the void crystal block on the server im on but after I gave the material to my friend and he put them in the empowerer it worked. After that whenever I tried the recipe on my own it worked on the server. However, when I made a single player world and tested it out again it didn't work.
**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
It sounds like you're either missing the scripts folder, or you've set it up incorrectly in your single player world :)
