### ISSUE TITLE
Startup log is full of issues/errors (fresh download)

### ISSUE THREAD

**Issue by krustymk** [NillerMedDild/Enigmatica2ExpertSkyblock#557]
**Modpack version**
1.35

**Issue**
Startup log is full of errors, seemed to play ok till it was time to exit then froze/crashed, ill add a shutdown/crash log later if it does that again

**Logs**
https://paste.ee/p/x5ohZ

**Comment by NillerMedDild** [comment]
Issues and errors in the log is very normal in modded Minecraft, as long as you're not experiencing any issues you can safely ignore them :)
