### ISSUE TITLE
Just a Question

### ISSUE THREAD

**Issue by CowHItFace** [NillerMedDild/Enigmatica2ExpertSkyblock#558]
I am wondering:
How did you guys setup the spawn mechanics for multiplayer servers. I simply want to find out, how every new player gets an own Island on the server. I am struggling to find a solution for that. 
Would be cool If you could andere this Question ^^

**Comment by NillerMedDild** [comment]
There's a guide in the server files :)

**Comment by CowHItFace** [comment]
Aight thanks ^^
