### ISSUE TITLE
Draconic Evolution Fusion Crafting Core is uncraftable (Extended Crafting)

### ISSUE THREAD

**Issue by Philenst** [NillerMedDild/Enigmatica2ExpertSkyblock#559]
**Modpack version**
1.35

**Issue**
Draconic Evolution Fusion Crafting Core is uncraftable following the items shown in the preview and in the tooltip. Tried in Multiplayer thinking it may be disabled, however same result in Singleplayer.
https://i.imgur.com/W0rH7jF.jpg
https://i.imgur.com/dklIBnb.png

Only have 20 pedestals set up and all recognised, however recipe still not recognised.

https://i.imgur.com/hkz3xhW.png

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Thanks for the report. Quick question, did you remember to supply the Crafting Core with power?

**Comment by Philenst** [comment]
Can confirm. I placed a creative cell under the Crafting Core and I tried other methods such as flux points aswell, same result unfortunately.

**Comment by NillerMedDild** [comment]
Huh, that's weird. I haven't updated the modpack in ages, I'm surprised this hasn't been reported earlier.

**Comment by NillerMedDild** [comment]
Works just fine for me :)
![billede](https://user-images.githubusercontent.com/21295394/83953995-69d50780-a845-11ea-830a-8ddd2752acbf.png)
