### ISSUE TITLE
Abnormal exit

### ISSUE THREAD

**Issue by Aleks233** [NillerMedDild/Enigmatica2ExpertSkyblock#561]
**Modpack version**
1.3.5

**Issue**
Game abnormal exit

**Logs**
The error file is attached
[crash-2020-07-25_17.13.54-server.txt](https://github.com/NillerMedDild/Enigmatica2ExpertSkyblock/files/4975246/crash-2020-07-25_17.13.54-server.txt)

**Comment by NillerMedDild** [comment]
I'm afraid we can't do anything about that crash, it's too generic :/ sorry!

**Comment by Aleks233** [comment]
OK,,,,,,
