### ISSUE TITLE
Glass doesnt convert into Crystal Shards in Alchemical Fusion Table

### ISSUE THREAD

**Issue by Craftingblubb** [NillerMedDild/Enigmatica2ExpertSkyblock#562]
**Modpack version**
1.35

**Issue**
I put 1 glass in the Alchemical Fusion Table put the Primus Alchemical Dust in the Fuel slot and it started working but when it finished there was no output and the glass item wasnt there, too although it was displayed

**Logs**
not available

**Comment by NillerMedDild** [comment]
I'm fairly certain that this is working, so I will redirect you to our Discord for support :)
