### ISSUE TITLE
Empowered Void Crystals not craftable using quarks basalt

### ISSUE THREAD

**Issue by ReluctantSniper** [NillerMedDild/Enigmatica2ExpertSkyblock#563]
**Modpack version**

v. 1.35
**Issue**

The Empowerer cannot craft empowered void crystals using basalt from any mod other than chisel, however draconic fusion crafting and extended crafting's combination crafting can both use any basalt. The empowerer is missing the "accepts any: stoneBasalt" tag. I believe this to be a bug, as chisel basalt is not craftable in skyblock, only quark's version is. The workaround is to batch craft basalt and chisel stacks at a time.
**Logs**

N/A

**Comment by NillerMedDild** [comment]
I'm sorry but E2ES will most likely not receive any more updates, I'm quite busy with 1.15+

**Comment by NillerMedDild** [comment]
Putting this in any `.zs` file in the `scripts` folder would fix the issue:
```zenscript
# Void
mods.actuallyadditions.Empowerer.removeRecipe(<actuallyadditions:item_crystal_empowered:3>);
mods.actuallyadditions.Empowerer.removeRecipe(<actuallyadditions:block_crystal_empowered:3>);

for item in <ore:stoneBasalt>.items {
	mods.actuallyadditions.Empowerer.addRecipe(<actuallyadditions:item_crystal_empowered:3>, <actuallyadditions:item_crystal:3>, <minecraft:dye>, <extendedcrafting:storage>, item, <actuallyadditions:block_misc:2>, 250000, 100, [0.1, 0.0, 0.0]);
	mods.actuallyadditions.Empowerer.addRecipe(<actuallyadditions:block_crystal_empowered:3>, <actuallyadditions:block_crystal:3>, <minecraft:dye>, <extendedcrafting:storage>, item, <actuallyadditions:block_misc:2>, 2500000, 200, [0.1, 0.0, 0.0]);
}
```

**Comment by ReluctantSniper** [comment]
i understand, and i appreciate you taking the time to provide a simple fix anyways, thanks!
