### ISSUE TITLE
My hand was removed and I can’t get to the end

### ISSUE THREAD

**Issue by moocowlot** [NillerMedDild/Enigmatica2ExpertSkyblock#564]
**Modpack version**
1.35

**Issue**
Hello my hand was removed and since then I have been able to access certain machines and other things like the end portal or end cake

**Comment by NillerMedDild** [comment]
Your hand was removed, huh? 
Have you tried restarting the game?

**Comment by moocowlot** [comment]
Yes I lit is like the F1 thing but i still have things like my hot at and map and health

**Comment by moocowlot** [comment]
I have figured out what is removing my hand and it is the environmental tech nano beacon  even though I don't have a invisibility upgrade but I still can't figure out the end thing

**Comment by NillerMedDild** [comment]
>  Have you tried restarting the game?
