### ISSUE TITLE
Thaumonomicum BUG

### ISSUE THREAD

**Issue by SCASCU** [NillerMedDild/Enigmatica2ExpertSkyblock#567]
Version 1.35

i play the modpack now like 4 days and i tried too get a Thaumonomicum by klinking on a bookshelf with salis mundus or the thaumcraft cauldron by clicking with salis mundus and nothing is wotking i cant get the cauldron and the book

**Comment by NillerMedDild** [comment]
I recommend you follow the Thaumcraft quests :)
