### ISSUE TITLE
Infinity lava Production

### ISSUE THREAD

**Issue by KacproPL132** [NillerMedDild/Enigmatica2ExpertSkyblock#568]
**Modpack version**
1.35

**Issue**
When dropping Blaze Powder Block to crucible when next to it is placed Vacuum Hopper from OpenBlocks, Lava starts to produce in it, but Blaze Powder Block is duplicated to Vacuum Hopper. [Watch vid https://youtu.be/752WumK8Zj8]
PS: I think giving link to youtube is better idea than giving this video to download in ZIP or something.

**Comment by NillerMedDild** [comment]
I'm sorry but E2ES will most likely not receive any more updates, I'm quite busy with 1.16
But thank you for the bug report.
