### ISSUE TITLE
Possible issue with JourneyMap 7.5.1

### ISSUE THREAD

**Issue by MJDeveloping** [NillerMedDild/Enigmatica2ExpertSkyblock#585]
**Modpack version**
1.36a (Latest)

**Issue**
We updated from JourneyMap 7.5.0 to JourneyMap 7.5.1 in version 1.36 I believe. Today I tried teleporting using JourneyMap and I get the error 
```
/jtp failed 
Usage: /jtp <x y z dim>
```

The reason I call this a "possible issue" is that I'm also dealing with a corrupt chunk in the same area... fixing that is my priority, rather than testing this. I will update the issue once I've tested it

P.s. The corrupted chunk is unlikely to be the fault of the modpack... I just pulled a stupid move and had multiblocks crossing chunks. Unless that's been fixed, that's probably what caused the corruption...

**Comment by NillerMedDild** [comment]
That sucks :/ As a workaround you can use another interdimensional tp command: `/rft rfttp x y z dim` iirc
If this is a JM issue, it most likely will not be solved tbh - The last JM version for 1.12.2 is a year old.

**Comment by MJDeveloping** [comment]
Yeah. The only thing that changed in this version is an "API fix", so might be worth reverting to the previous version whenever the next update is needed :) I just reverted to the previous version on my end, no problems
