### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Chili1998** [NillerMedDild/Enigmatica2ExpertSkyblock#586]
**Modpack version**
Version 1.36a

**Issue**
Just updated from Version 1.35 to 1.36a.
When I try to launch the game it crashes instantly before even showing the game screen that shows the initializing phases. Doesn't show a crash report just "Exit Code:0"

**Comment by NillerMedDild** [comment]
Please supply your latest.log :)

**Comment by Chili1998** [comment]
[latest.log](https://github.com/NillerMedDild/Enigmatica2ExpertSkyblock/files/6164287/latest.log)
Sorry, forgot to add it xD

**Comment by Chili1998** [comment]
Thanks :D

**Comment by NillerMedDild** [comment]
I think reinstalling it ought to help :) Could you please let me know if that helps?
