### ISSUE TITLE
1.36a Requires a Missing Dependency

### ISSUE THREAD

**Issue by Sparktion** [NillerMedDild/Enigmatica2ExpertSkyblock#587]
**Modpack version**
1.36a
**Issue**
1.36a Requires Missing Dependency:

![unknown](https://user-images.githubusercontent.com/59346386/111880277-7b247600-8978-11eb-9c6f-a3909080d20c.png)

After repairing minecraft installation, which is done from the 3 dots in the corner, you receive another error:

![image](https://user-images.githubusercontent.com/59346386/111880265-66e07900-8978-11eb-93e7-cf2f76ca773b.png)

**Logs**
The game does not start. Errors happen during the updating process.

**Comment by NillerMedDild** [comment]
Looks like CurseForge being CurseForge :P 
Reinstall, if that doesn't work wait an hour or so and try again :)

**Comment by Sparktion** [comment]
I found a temporary fix, download the pack from the website and import it as a custom profile.

**Comment by Sparktion** [comment]
> Looks like CurseForge being CurseForge :P
> Reinstall, if that doesn't work wait an hour or so and try again :)
I found a temporary fix, download the pack from the website and import it as a custom profile.
