### ISSUE TITLE
[1.36] Nutrition mod is missing

### ISSUE THREAD

**Issue by pha3l** [NillerMedDild/Enigmatica2ExpertSkyblock#591]
**Modpack version**
1.36

**Issue**
Nutrition mod seems to be missing.  I still see config for it (and also a bugfix related to it in the latest patch notes) so I assume it's still supposed to be there. I know it's not on Curseforge so I'm not sure what the mechanism for including stuff like that in a pack is, so it could be a Curseforge issue rather than yours.

**Comment by NillerMedDild** [comment]
Nutrition is not a part of this modpack, the config must've been brought over from E2E at some point :)

**Comment by pha3l** [comment]
Bit confused about that, in this issue there was a fix applied to the configuration for Nutrition for this modpack specifically. 
 https://github.com/NillerMedDild/Enigmatica2ExpertSkyblock/pull/572
 
 Also, in prior versions of the modpack (i.e. `1.30`) it was present in the `mods` folder.
 
 Regardless, if it's removal was intentional, no worries!  Thanks for the awesome work, looking forward to the new expert pack!
