### ISSUE TITLE
Bean seeds (Harvestcraft) from Market (Farming for Blockheads) grows Beans (Random things)

### ISSUE THREAD

**Issue by HaxtonSale1** [NillerMedDild/Enigmatica2ExpertSkyblock#597]
### Modpack Version

1.36a

### Describe your issue.

> Beast — Today at 10:22 AM
> Anyone have any idea where to find the beans from pam's harvest in Enigmatica 2 expert skyblock? JEI says shaded gardens are on planet stella but i have been looking for quite some time with so success.
> Haxton — Today at 10:33 AM
> I have never played E2ES but: Market (Farming for blockheads)?
> Beast — Today at 10:34 AM
> it has beans but it is unfortunately not the right "bean"
> ..apparently, even though it is a pam's harvest bean seed
> it grows the random things bean

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thanks for the report. I'm afraid I will not be fixing this, as I do not have the time. Sorry.

**Comment by HaxtonSale1** [comment]
understandable, have a nice day
