### ISSUE TITLE
UU Matter Replication Tooltips

### ISSUE THREAD

**Issue by Us3rNqmed** [NillerMedDild/Enigmatica2ExpertSkyblock#599]
### Describe your suggestion

it would be really nice to make them replicateable like E2E :)

### Why would you like this added/changed?

it would make life much easier as e2e

**Comment by NillerMedDild** [comment]
What Machine Frames? The ones from Thermal can be replicated :)

**Comment by Us3rNqmed** [comment]
the ones from thermal dont show that they can be replicated, (atleast for me)

**Comment by NillerMedDild** [comment]
As in, they have no tooltip?

**Comment by NillerMedDild** [comment]
Ah yes, there is no tooltip in E2ES, I'll fix that real quick.

**Comment by Us3rNqmed** [comment]
thanks :)
